/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Hacking": "黑客攻击",
    "Click on this to upgrade your Source-File -1!": "单击此按钮可升级您的源文件 -1！",
    "City": "城市",
    "Hacknet": "黑客网",
    "Options": "选项",
    "Loading Bitburner v": "加载 比特燃烧器",
    "Script Editor": "脚本编辑器",
    "SKIP TUTORIAL": "跳过教程",
    "Stats": "统计",
    "Terminal": "终端",
    "This tutorial will show you the basics of the game. You may skip the tutorial at any time.": "本教程将向您展示游戏的基础知识。 您可以随时跳过本教程。",
    "to temporarily hide this tutorial.": "暂时隐藏本教程。",
    "Travel": "旅行",
    "Tutorial": "教程",
    "Welcome to Bitburner, a cyberpunk-themed incremental RPG! The game takes place in a dark, dystopian future... The year is 2077...": "欢迎来到以赛博朋克为主题的增量 RPG 游戏 比特燃烧器！ 游戏发生在一个黑暗、反乌托邦的未来……那一年是 2077 年……",
    "World": "世界",
    "You can also click the eye symbol": "您也可以单击眼睛符号",
    ", your Hacknet Nodes generated": ", 你的 黑客网 节点生成",
    ". While you were offline, your scripts generated": ". 当您离线时，您的脚本会生成",
    "Active Scripts": "活动的脚本",
    "Character": "角色",
    "Help": "帮助",
    "Offline for": "离线了 ",
    "reputation divided amongst your factions.": "声望在你的阵营之间分配。",
    "and you gained": "并且你获得了",
    "net": "网络",
    "MAX": "最大",
    "Misc": "杂项",
    "Multipliers": "乘数",
    "Production": "生产",
    "The Hacknet is a global, decentralized network of machines. It is used by hackers all around the world to anonymously share computing power and perform distributed cyberattacks without the fear of being traced.": "黑客网 是一个全球性的、去中心化的机器网络。 世界各地的黑客都使用它来匿名共享计算能力并执行分布式网络攻击，而无需担心被追踪。",
    "Total Time played": "总游戏时长",
    "Travel Agency": "旅行社",
    "Time played since last Augmentation": "自上次增强以来的游戏时间",
    "Node": "节点",
    "Nodes": "节点",
    "Current City": "当前城市",
    "Crime success multiplier": "犯罪成功乘数",
    "Crime money multiplier": "犯罪金钱乘数",
    "Company reputation gain multiplier": "公司声誉增益倍数",
    "exp": "经验值",
    "Faction reputation gain multiplier": "阵营声望增益乘数",
    "Game Saved!": "游戏已保存！",
    "General": "常规",
    "Here, you can purchase a Hacknet Node, a specialized machine that can connect and contribute its resources to the Hacknet network. This allows you to take a small percentage of profits from hacks performed on the network. Essentially, you are renting out your Node's computing power.": "在这里，您可以购买 黑客网 节点，这是一种可以连接 黑客网 网络并将其资源贡献给 黑客网 网络的专用机器。 这使您可以从网络上执行的黑客攻击中获得一小部分利润。 本质上，您是在出租 节点 的计算能力。",
    "Each Hacknet Node you purchase will passively earn you money. Each Hacknet Node can be upgraded in order to increase its computing power and thereby increase the profit you earn from it.": "您购买的每个 黑客网 节点都会被动地为您赚钱。 每个 黑客网 节点都可以升级以提高其计算能力，从而增加您从中获得的利润。",
    "ing": "",
    "Use \"nano [File Name]\" in the terminal to open files": "在终端中使用\"nano [文件名]\"打开文件",
    "Total Hacknet": "总黑客网",
    "Save & Close (Ctrl/Cmd + s": "保存 & 关闭 (Ctrl/Cmd + s",
    "Salary multiplier": "工资乘数",
    "Documentation": "文档",
    "From here, you can travel to any other city! A ticket costs": "从这里，您可以前往任何其他城市！ 一张票的费用",
    "Full": "满了",
    "Loading script editor!": "加载脚本编辑器！",
    "No open files": "没有打开文件",
    "Theme editor": "主题编辑器",
    "Terminal capacity": "终端容量",
    "Suppress travel confirmations": "禁止 旅行确认",
    "Suppress story messages": "禁止 故事 消息",
    "Suppress Saved Game Toast": "禁止 保存游戏 提示",
    "Suppress faction invites": "禁止 阵营邀请",
    "Suppress augmentations confirmation": "禁止 增强确认",
    "Suppress TIX messages": "禁止 TIX 消息",
    "Save Game": "保存游戏",
    "Save game on file save": "在文件保存时保存游戏",
    "Report bug": "报告Bug",
    "Soft Reset": "软重置",
    "Disable text effects": "禁用文本效果",
    "Disable hotkeys": "禁用快捷键",
    "Disable ascii art": "禁用ASCII艺术",
    "Diagnose files": "文件诊断",
    "Delete Game": "删除存档",
    "Netscript exec time (ms": "网络脚本 执行时间（毫秒",
    "Netscript log size": "网络脚本日志大小",
    "Netscript port size": "网络脚本端口大小",
    "The maximum number of entries that can be written to a the terminal. Setting this too high can cause the game to use a lot of memory.": "可以写入终端的最大条目数。 将此值设置得太高会导致游戏使用大量内存。",
    "The time (in seconds) between each autosave. Set to 0 to disable autosave.": "每次自动保存之间的时间（以秒为单位）。 设置为 0 以禁用自动保存。",
    "Apply for Agent Job": "申请代理工作",
    "Apply for IT Job": "申请IT工作",
    "Apply for Security Job": "申请保安工作",
    "Apply for Software Job": "申请软件工作",
    "Central Intelligence Agency": "中央情报局",
    "Requires": "需要",
    "Return to World": "返回到世界",
    "Let's start by heading to the Stats page. Click": "让我们首先前往统计页面。 点击",
    "on the main navigation menu (left-hand side of the screen": "在主导航菜单（屏幕左侧）",
    "Beautify": "美化",
    "Enter to Rename, ⇧Enter to Preview": "回车重命名，⇧回车预览",
    "Press space bar to start a drag.\n  When dragging you can use the arrow keys to move the item around and escape to cancel.\n  Some screen readers may require you to be in focus mode or to use your pass through key": "按空格键开始拖动。\n 拖动时，您可以使用箭头键移动项目并退出以取消。\n 某些屏幕阅读器可能要求您处于焦点模式或使用传递键",
    "Recent": "最近",
    "Rows per page": "每页行数",
    "This page displays a list of all of your scripts that are currently running across every machine. It also provides information about each script's production. The scripts are categorized by the hostname of the servers on which they are running.": "此页面显示当前在每台机器上运行的所有脚本的列表。 它还提供有关每个脚本制作的信息。 脚本按运行它们的服务器的主机名分类。",
    "Total production since last Augment Installation": "自上次安装以来的总产量",
    "Active": "活动中",
    "Apply for Business Job": "申请商务工作",
    "Apply to be a part-time Employee": "申请成为兼职员工",
    "Apply to be an Employee": "申请成为员工",
    "Basic": "基础",
    "Blade Industries": "刀片工业",
    "FoodNStuff": "食品厂",
    "Hospital": "医院",
    "Get treatment for wounds -": "接受伤口治疗 —",
    "Iron Gym": "铁之健身房",
    "Infiltrate Company": "渗透公司",
    "Joe's Guns": "乔的枪",
    "Total": "总计",
    "Train Agility (": "训练 敏捷 (",
    "Train Defense (": "训练 防御 (",
    "Train Dexterity (": "训练 灵巧 (",
    "Train Strength (": "训练 力量 (",
    " earned since you last installed Augmentations": "自您上次安装 加薪 以来赚取的收入",
    "[blade industries]": "[刀片产业]",
    "Welcome to the World Stock Exchange (WSE)!": "欢迎来到 世界证券交易所（WSE）！",
    "Aevum": "艾维姆",
    "Buy 4S Market Data TIX API Access - ": "购买 4S 市场数据 贸易信息交换(TIX) API 访问权限 - ",
    "Buy 4S Market Data Access - ": "购买4S市场数据访问权限 - ",
    "Buy Trade Information eXchange (TIX) API Access - ": "购买 贸易信息交换(TIX) API 访问权限 - ",
    "Buy WSE Account - ": "购买 世界证券交易所（WSE） 账户 - ",
    "Chongqing": "重庆",
    "commission fee.": "佣金费。",
    "Commission Fees: Every transaction you make has a": "佣金费用：您进行的每笔交易都有一个",
    "DeltaOne": "达美航空",
    "Four Sigma (4S) Market Data Feed": "四西格码 (4S) 市场数据馈送",
    "Four Sigma's (4S) Market Data Feed provides information about stocks that will help your trading strategies.": "四西格码 (4S) 市场数据馈送提供有助于您的交易策略的股票信息。",
    "Investopedia": "投资百科",
    "New Tokyo": "新东京",
    "Ishima": "伊岛",
    "TIX, short for Trade Information eXchange, is the communications protocol used by the WSE. Purchasing access to the TIX API lets you write code to create your own algorithmic/automated trading strategies.": "TIX 是 贸易信息交换 的缩写，是 世界证券交易所（WSE） 使用的通信协议。 通过购买 贸易信息交换(TIX) API 访问权限，您可以编写代码来创建自己的算法/自动交易策略。",
    "To begin trading, you must first purchase an account": "要开始交易，您必须先购买一个账户",
    "Trade Information eXchange (TIX) API": "贸易信息交换 (TIX) API",
    "Volhaven": "沃尔黑文",
    "WARNING: When you reset after installing Augmentations, the Stock Market is reset. You will retain your WSE Account, access to the TIX API, and 4S Market Data access. However, all of your stock positions are lost, so make sure to sell your stocks before installing Augmentations!": "警告：当您在安装 加薪 后重置时，股票市场将被重置。 您将保留您的 世界证券交易所（WSE） 帐户、对 贸易信息交换 (TIX) API 的访问权限和 4S 市场数据访问权限。 但是，您的所有股票头寸都将丢失，因此请确保在安装增强功能之前卖出您的股票！",
    "Augmentations": "加薪",
    "Companies": "公司",
    "Complete list of functions": "完整的功能列表",
    "Donate blood!": "献血！",
    "Enable bash hotkeys": "启用 bash 快捷键",
    "export": "导出",
    "Factions": "阵营",
    "Force kill all active scripts": "强制杀掉所有活动的脚本",
    "Forcefully kill all active running scripts, in case there is a bug or some unexpected issue with the game. After using this, save the game and then reload the page. This is different then normal kill in that normal kill will tell the script to shut down while force kill just removes the references to it (and it should crash on it's own). This will not remove the files on your computer. Just forcefully kill all running instance of all scripts.": "强行杀掉所有正在运行的脚本，以防游戏出现错误或一些意外问题。 使用后，保存游戏，然后重新加载页面。 这与正常终止不同，正常终止会告诉脚本关闭，而强制终止只是删除对它的引用（并且它应该自行崩溃）。 这不会删除您计算机上的文件。 只需强行杀死所有脚本的所有正在运行的实例。",
    "Gain root access on CSEC": "获得 CSEC 的 root 访问权限",
    "Getting Started": "入门",
    "hydroflame (Current maintainer": "水焰 (当前维护者",
    "If this is set all ASCII art will be disabled.": "如果设置了此项，则所有 ASCII 艺术作品都将被禁用。",
    "If this is set, text effects will not be displayed. This can help if text is difficult to read in certain areas.": "如果设置了此项，则不会显示文本效果。 如果文本在某些区域难以阅读，这会有所帮助。",
    "Improved Bash emulation mode. Setting this to 1 enables several new Terminal shortcuts and features that more closely resemble a real Bash-style shell. Note that when this mode is enabled, the default browser shortcuts are overriden by the new Bash shortcuts.": "改进的 Bash 仿真模式。 将此设置为 1 会启用几个新的终端快捷方式和功能，它们更类似于真正的 Bash 风格的 shell。 请注意，启用此模式后，默认浏览器快捷方式将被新的 Bash 快捷方式覆盖。",
    "If this is set, the confirmation message before buying augmentation will not show up.": "如果设置，则不会显示购买增强前的确认消息。",
    "If this is set, the confirmation message before traveling will not show up. You will automatically be deducted the travel cost as soon as you click.": "如果设置了此项，则不会显示出行前的确认信息。您将在您点击后自动扣除差旅费用。",
    "If this is set, the stock market will never create any popup.": "如果设置了这个，股票市场将永远不会创建任何弹出窗口。",
    "If this is set, then any faction invites you receive will not appear as popups on the screen. Your outstanding faction invites can be viewed in the 'Factions' page.": "如果设置了这一点，那么您收到的任何派系邀请都不会在屏幕上显示为弹出窗口。您可以在“派系”页面中查看您出色的派系邀请。",
    "If this is set, then any messages you receive will not appear as popups on the screen. They will still get sent to your home computer as '.msg' files and can be viewed with the 'cat' Terminal command.": "如果已设置，则您收到的任何消息都不会在屏幕上显示为弹出窗口。它们仍会作为“.msg”文件发送到您的家用计算机，并且可以使用“cat”终端命令进行查看。",
    "If this is set, then most hotkeys (keyboard shortcuts) in the game are disabled. This includes Terminal commands, hotkeys to navigate between different parts of the game, and the \"Save and Close (Ctrl + b)\" hotkey in the Text Editor.": "如果设置了此项，则游戏中的大多数热键（键盘快捷键）将被禁用。这包括终端命令、在游戏不同部分之间导航的热键，以及文本编辑器中的“保存并关闭 (Ctrl + b)\”热键。",
    "If this is set, there will be no \"Saved Game\" toast appearing after save.": "如果设置了此项，保存后将不会出现“已保存的游戏”吐司。",
    "If your save file is extremely big you can use this button to view a map of all the files on every server. Be careful there might be spoilers.": "如果您的保存文件非常大，您可以使用此按钮查看每台服务器上所有文件的地图。小心可能有剧透。",
    "import": "进口",
    "Incremental game plaza": "增量游戏广场",
    "Infiltration": "渗透",
    "Keyboard Shortcuts": "键盘快捷键",
    "Milestones don't reward you for completing them. They are here to guide you if you're lost. They will reset when you install Augmentations.": "里程碑不会奖励您完成它们。如果您迷路了，他们会在这里为您提供指导。当您安装增强功能时，它们将重置。",
    "Netscript Programming Language": "网络脚本 编程语言",
    "NS1 vs NS2 (or .script vs .js": "NS1 与 NS2（或 .script 与 .js",
    "Perform a soft reset. Resets everything as if you had just purchased an Augmentation.": "执行软复位。重置所有内容，就像您刚刚购买了增强功能一样。",
    "Save your game any time a file is saved in the script editor.": "在脚本编辑器中保存文件时，随时保存您的游戏。",
    "Scripts": "脚本",
    "Servers & Networking": "服务器和网络",
    "Simplified list of functions": "简化的功能列表",
    "Soft reset and Restart tutorial": "软复位和重启教程",
    "Terminal commands and log entries will be timestamped. See https://date-fns.org/docs/Getting-Started/": "终端命令和日志条目将带有时间戳。见 https://date-fns.org/docs/Getting-Started/",
    "The maximum number of entries that can be written to a port using Netscript's write() function. Setting this too high can cause the game to use a lot of memory.": "可以使用 网络脚本 的 write() 函数写入端口的最大条目数。将此值设置得太高会导致游戏使用大量内存。",
    "The maximum number of lines a script's logs can hold. Setting this too high can cause the game to use a lot of memory if you have many scripts running.": "脚本日志可以容纳的最大行数。如果您有许多脚本在运行，则将此值设置得太高会导致游戏使用大量内存。",
    "The minimum number of milliseconds it takes to execute an operation in Netscript. Setting this too low can result in poor performance if you have many scripts running.": "在 网络脚本 中执行操作所需的最小毫秒数。如果您有许多脚本正在运行，则将此值设置得太低会导致性能不佳。",
    "This will reset all your stats to 1 and money to 1k. Are you sure?": "这会将您的所有统计数据重置为 1，将金钱重置为 1k。你确定吗？",
    "Timestamp format: ": "时间戳格式：",
    "Traveling": "旅行",
    "Tutorial / Documentation": "教程/文档",
    "Level": "等级",
    "Cores": "核心",
    "RAM": "内存",
    "Cancel": "取消",
    "Difficulty": "困难",
    "Four Sigma": "四西格玛",
    "Everything that uses arrow can also use WASD": "使用箭头的所有东西也可以使用 WASD",
    "Get Ready!": "准备好！",
    "Infiltrating": "渗透",
    "Infiltration is a series of short minigames that get progressively harder. You take damage for failing them. Reaching the maximum level rewards you with intel you can trade for money or reputation.": "渗透是一系列越来越难的短小游戏。 你会因为失败而受到伤害。 达到最高级别会奖励您可以交易金钱或声誉的情报。",
    "Maximum level": "最高级别",
    "MOTHERBOARD ROOT JUNKMAIL FORMAT": "主板根垃圾邮件格式",
    "No game require use of the mouse.": "没有游戏需要使用鼠标。",
    "Sometimes the rest of the keyboard is used.": "有时会使用键盘的其余部分。",
    "Spacebar is the default action/confirm button.": "空格键是默认的操作/确认按钮。",
    "The minigames you play are randomly selected. It might take you few tries to get used to them.": "您玩的小游戏是随机选择的。 您可能需要几次尝试才能习惯它们。",
    "Trivial    Normal        Hard    Impossible": "简单    正常        困难    噩梦",
    "Type it backward": "向后输入",
    "Warning: This location is too heavily guarded for your current stats, try training or finding an easier location.": "警告：对于您当前的统计数据，此位置戒备森严，请尝试训练或寻找更容易的位置。",
    "KILL": "杀掉",
    "Forcefully kill all running scripts? This will also save your game and reload the game.": "强行杀死所有正在运行的脚本？ 这也将保存您的游戏并重新加载游戏。",
    "Invalid path. Failed to change directories": "路径无效。 更改目录失败",
    "Apply for Software Consultant Job": "申请软件顾问工作",
    "Carmichael Security": "卡迈克尔保安",
    "Gain hacking experience!": "获得黑客经验！",
    "Icarus Microsystems": "伊卡洛斯微系统公司",
    "Powerhouse Gym": "强力健身房",
    "Rothman University": "罗斯曼大学",
    "Stop taking course": "停止学习",
    "Stop training at gym": "停止在健身房训练",
    "Study Computer Science (free": "学习计算机科学（免费",
    "studying Computer Science": "学习计算机科学",
    "Take Algorithms course (": "参加算法课程（",
    "Take Data Structures course (": "参加数据结构课程（",
    "Take Leadership course (": "参加领导力课程（",
    "Take Management course (": "参加管理课程（",
    "Take Networks course (": "参加网络课程（",
    "This has cost you": "这让你付出了代价",
    "training your strength at a gym": "在健身房锻炼你的力量",
    "Unforunately, you do not qualify for this position": "很遗憾，您不符合此职位的资格",
    "Universal Energy": "环球能源",
    "You have been": "你已经",
    "You have gained": "你获得了",
    "You may cancel at any time": "你可以随时取消",
    "for": "",
    "/ sec) agility exp": "/秒) 敏捷经验",
    "/ sec) charisma exp": "/秒) 魅力经验",
    "/ sec) defense exp": "/秒) 防御经验",
    "/ sec) dexterity exp": "/秒) 灵巧经验",
    "/ sec) hacking exp": "/秒) 黑客经验",
    "/ sec) strength exp": "/秒) 力量经验",
    "agility experience": "敏捷经验",
    "Assassinate (": "暗杀（",
    "Attempt to commit armed robbery on a high-end store": "企图在高档商店持械抢劫",
    "Attempt to mug a random person on the street": "试图在街上随意抢劫一个人",
    "Attempt to rob property from someone's house": "企图从某人的房子里抢劫财物",
    "Attempt to shoplift from a low-end retailer": "试图从低端零售商处入店行窃",
    "Bond Forgery (": "债券伪造（",
    "Cancel crime": "取消犯罪",
    "chance of success": "成功的机会",
    "charisma experience": "魅力经验",
    "Crime successful!": "犯罪成功！",
    "Deal Drugs (": "Du品交易 (",
    "defense experience": "防御经验",
    "dexterity experience": "灵巧经验",
    "Grand theft Auto (": "侠盗猎车手 （",
    "hacking experience": "黑客经验",
    "Heist (": "抢劫 (",
    "Homicide (": "凶杀案（",
    "Kidnap and Ransom (": "绑架和赎金（",
    "Larceny (": "盗窃 (",
    "Mug someone (": "抢劫某人(",
    "National Security Agency": "国家安全局",
    "Rob store (": "抢劫商店（",
    "shoplift": "入店行窃",
    "Shoplift (": "入店行窃 (",
    "strength experience": "力量经验",
    "The Slums": "贫民窟",
    "Time remaining": "剩余时间",
    "Traffick illegal Arms (": "贩卖非法武器（",
    "You are attempting to": "你正试图",
    "You gained": "你获得了",
    "Crime failed!": "犯罪失败！",
    "rob a store": "抢劫商店",
    "Attempt to assassinate a high-profile target": "企图暗杀一个备受瞩目的目标",
    "Attempt to commit grand theft auto": "企图实施侠盗猎车",
    "Attempt to deal drugs": "尝试贩毒",
    "Attempt to forge corporate bonds": "试图伪造公司债券",
    "Attempt to kidnap and ransom a high-profile-target": "企图绑架和勒索一个备受瞩目的目标",
    "Attempt to murder a random person on the street": "试图在街上随意谋杀一个人",
    "Attempt to pull off the ultimate heist": "尝试完成终极抢劫",
    "Attempt to smuggle illegal arms into the city": "企图将非法武器走私进城",
    "Remaining": "剩余",
    "Progress": "进度",
    "Gain charisma experience!": "获得魅力经验！",
    "Requires TIX API Access": "需要 TIX API 访问权限",
    "You are currently working as a": "您目前的工作是",
    "You have been working for": "你工作了 ",
    "You have earned": "你赚了",
    "You will automatically finish after working for 8 hours. You can cancel earlier if you wish, but you will only gain": "您将在工作 8 小时后自动完成。 如果您愿意，您可以提前取消，但您只会获得",
    "(Current Company Reputation": "（目前公司声誉",
    ") agility exp": ") 敏捷经验",
    ") charisma exp": ") 魅力经验",
    ") defense exp": ") 防御经验",
    ") dexterity exp": ") 灵巧经验",
    ") hacking exp": ") 黑客经验",
    ") reputation for this company": ") 这家公司的声誉",
    ") strength exp": ") 力量经验",
    "Company Favor": "公司青睐",
    "Company reputation": "公司声誉",
    "Congratulations, you are now employed at Joe's Guns": "恭喜你，你现在就职于 Joe's Guns",
    "Do something else simultaneously": "同时做其他事情",
    "Employee": "员工",
    "half": "一半",
    "Job": "工作",
    "Job Title": "职称",
    "of the reputation you've earned so far.": "您迄今为止所获得的声誉。",
    "Quit": "退出",
    "Stop Working": "停止工作",
    "Work": "工作",
    "mug someone": "抢劫某人",
    "Job you last worked": "你上次工作的职位",
    "Focus": "集中",
    "Employer at which you last worked": "您上次工作的雇主",
    "commit larceny": "盗窃",
    "All Employers": "所有雇主",
    "rep": "代理",
    "Part-time Employee": "兼职员工",
    "You will have": "你将会拥有",
    "company favor upon resetting after installing Augmentations": "安装 加薪 后重置时公司青睐",
    "Congratulations, you are now employed at FoodNStuff": "恭喜你，你现在就职于 食品厂",
    "A stock's price forecast can change over time. This is also affected by volatility. The more volatile a stock is, the more its price forecast will change.": "股票的价格预测会随着时间而改变。 这也受到波动性的影响。 一只股票的波动性越大，其价格预测的变化就越大。",
    "Access to the 4S Market Data feed will display two additional pieces of information about each stock: Price Forecast & Volatility": "访问 4S 市场数据源将显示关于每只股票的两条额外信息：价格预测和波动率",
    "Price Forecast indicates the probability the stock has of increasing or decreasing. A '+' forecast means the stock has a higher chance of increasing than decreasing, and a '-' means the opposite. The number of '+/-' symbols is used to illustrate the magnitude of these probabilities. For example, '+++' means that the stock has a significantly higher chance of increasing than decreasing, while '+' means that the stock only has a slightly higher chance of increasing than decreasing.": "价格预测表示股票上涨或下跌的概率。 '+' 预测意味着该股票上涨的可能性大于下跌的可能性，而“-”则表示相反。 “+/-”符号的数量用于说明这些概率的大小。 例如，“+++”表示该股票上涨的机会明显高于下跌的机会，而“+”表示该股票的上涨机会仅略高于下跌的机会。",
    "Volatility represents the maximum percentage by which a stock's price can change every tick (a tick occurs every few seconds while the game is running).": "波动率表示股票价格每次变动的最大百分比（在游戏运行时每隔几秒发生一次变动）。",
    "taking a Data Structures course": "参加数据结构课程",
    "Upgrade 'home' cores (": "升级 “home” 核心（",
    "Upgrade 'home' RAM (": "升级 “home” 内存（",
    "A business man is yelling at a clerk. You should come back later.": "一个商人正在对一个职员大喊大叫。 你应该晚点回来。",
    "Alpha Enterprises": "阿尔法公司",
    "Purchase": "购买",
    "\"Cores increase the effectiveness of grow() and weaken() on 'home'\"": "\"核心增加了'home'上grow()和weak()的有效性\"",
    "\"More RAM means more scripts on 'home'\"": "\"更多的内存意味着'home'上可以运行更多脚本\"",
    "\"You can order bigger servers via scripts. We don't take custom orders in person.\"": "\"您可以通过脚本订购更大的服务器。我们不会亲自接受定制订单。\"",
    "of RAM for": "内存 花费",
    "Please enter the server hostname below": "请在下面输入服务器主机名",
    "Would you like to purchase a new server with": "您想购买新服务器拥有",
    "TOR Router - Purchased": "TOR 路由器 - 已购买",
    "Use the scan/scan-analyze commands to search for the dark web connection.": "使用 scan/scan-analyze 命令搜索暗网连接。",
    "You have purchased a TOR router!": "您购买了 TOR 路由器！",
    "You now have access to the dark web from your home computer.": "您现在可以从家用计算机访问暗网。",
    "I know you can sense it. I know you're searching for it. It's why you spend night after night at your computer.": "我知道你能感觉到。 我知道你正在寻找它。 这就是为什么你夜复一夜地在电脑前度过的原因。",
    "It's real, I've seen it. And I can help you find it. But not right now. You're not ready yet.": "这是真的，我见过。 我可以帮你找到它。 但不是现在。 你还没准备好。",
    "Message received from unknown sender": "收到来自未知发件人的邮件",
    "taking a Networks course": "学习网络课程",
    "The fl1ght.exe program was added to your home computer": "fl1ght.exe 程序已添加到您的家用计算机",
    "This message was saved as j0.msg onto your home computer.": "此消息已作为 j0.msg 保存到您的家用计算机上。",
    "Use this program to track your progress": "使用此程序来跟踪您的进度",
    "% complete.": "% 已完成.",
    "Cancel work on creating program": "取消创建程序的工作",
    "Create program": "创建程序",
    "Create Program": "创建程序",
    "If you cancel, your work will be saved and you can come back to complete the program later.": "如果您取消，您的工作将被保存，您可以稍后回来完成程序。",
    "MegaCorp": "大型企业",
    "Soon you will be contacted by a hacking group known as CyberSec. They can help you with your search.": "很快，一个名为 CyberSec 的黑客组织将与您联系。 他们可以帮助您进行搜索。",
    "The program is": "该程序",
    "This page displays any programs that you are able to create. Writing the code for a program takes time, which can vary based on how complex the program is. If you are working on creating a program you can cancel at any time. Your progress will be saved and you can continue later.": "此页面显示您可以创建的所有程序。 为程序编写代码需要时间，具体时间会因程序的复杂程度而异。 如果您正在创建一个程序，您可以随时取消。 您的进度将被保存，您可以稍后继续。",
    "This program allows you to directly connect to other servers through the 'scan-analyze' command": "该程序允许您通过“scan-analyze”命令直接连接到其他服务器",
    "training your agility at a gym": "在健身房训练你的敏捷性",
    "training your defense at a gym": "在健身房训练你的防御",
    "training your dexterity at a gym": "在健身房训练你的灵巧",
    "You are currently working on coding": "您目前正在编写代码",
    "You should join them, garner their favor, and exploit them for their Augmentations. But do not trust them. They are not what they seem. No one is.": "您应该加入他们，赢得他们的青睐，并利用他们进行增强。 但不要相信他们。 他们不是他们看起来的那样。 没有人是。",
    " Nodes": " 节点",
    " Nodes Expenses": " 节点开支",
    "Class": "课程",
    "Company Work": "公司工作",
    "Crimes": "犯罪",
    "Other": "其它",
    "Hospitalization": "住院",
    "The new program can be found on your home computer.": "新程序可以在您的家用计算机上找到。",
    "taking an Algorithms course": "学习算法课程",
    "assassinate a high-profile target": "暗杀一个引人注目的目标",
    "commit grand theft auto": "犯下侠盗猎车手",
    "commit homicide": "谋杀",
    "Company favor increases the rate at which you earn reputation for this company by 1% per favor. Company favor is gained whenever you reset after installing Augmentations. The amount of favor you gain depends on how much reputation you have with the company.": "公司好感使您为该公司赢得声誉的速度提高 1%。 每当您在安装增强后重置时，都会获得公司青睐。 您获得的青睐程度取决于您在公司中的声誉。",
    "deal drugs": "Du品交易",
    "forge corporate bonds": "伪造公司债券",
    "kidnap someone for ransom": "绑架某人索要赎金",
    "pull off the ultimate heist": "完成终极抢劫",
    "taking an Algorithms course": "学习算法课程",
    "traffick illegal arms": "贩运非法武器",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Discord": "Discord",
    "Reddit": "Reddit",
    "options": "选项",
    "home": "home",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Hacking": "黑客攻击",
    "Hacknet": "黑客网",
    "Hack": "黑客",
    "Money": "钱",
    "Defense": "防御",
    "Def": "防御",
    "HP": "生命值",
    "Strength": "力量",
    "Str": "力量",
    "Agility": "敏捷",
    "Agi": "敏捷",
    "Dexterity": "灵巧",
    "Dex": "灵巧",
    "Changelog": "更新日志",
    "Character": "角色",
    "Charisma": "魅力",
    "Cha": "魅力",
    "Bitburner v": "比特燃烧器 v",
    "Servers owned: ": "拥有的服务器：",
    "Augmentations installed: ": "增强已安装：",
    "Timestamp format:": "时间戳格式：",
    "Locale": "语言",
    " Nodes owned:": " 拥有的节点：",
    " [hospital]": " [医院]",
    " [megacorp]": " [大型企业]",
    "[foodnstuff]": "[食品厂]",
    "[powerhouse gym]": "[强力健身房]",
    "[rothman university]": "[罗斯曼大学]",
    "[universal energy]": "[宇宙能量]",
    "Sector-": "扇区-",
    "Error: Invalid file. Only scripts (.script, .ns, .js), or text files (.txt) can be edited with ": "错误：无效的文件。 只能使用脚本（.script、.ns、.js）或文本文件 (.txt) 进行编辑",
    "RAM: ": "内存: ",
    "Autosave interval (": "自动保存间隔 (",
    "Completing ": "完成 ",
    "hacknet-node-": "黑客网-节点-",
    "You've been Hospitalized for ": "你因住院治疗花费 ",
    "Purchase Hacknet Node -": "购买 黑客网 节点 -",
    "Buy 4S Market Data Access -": "购买4S市场数据访问权限 -",
    "Buy 4S Market Data TIX API Access -": "购买 4S 市场数据 TIX API 访问权限 -",
    "Buy Trade Information eXchange (TIX) API Access -": "购买贸易信息交换 (TIX) API 访问 -",
    "Buy WSE Account -": "购买 世界证券交易所（WSE） 账户 -",
    "Congratulations, you are now employed part-time at FoodNStuff": "恭喜您，您现在在 食品厂 兼职",
    "Purchase TOR router -": "购买TOR路由器 -",
    "Server": "服务器",
    " successfully purchased with hostname ": " 成功购买主机 ",
    "taking a Leadership course": "学习领导力课程",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    " Chance multiplier": " 几率乘数",
    " Experience multiplier": " 经验乘数",
    " Level multiplier": " 等级乘数",
    " Speed multiplier": " 速度乘数",
    " Money multiplier": " 金钱乘数",
    " Growth multiplier": " 成长乘数",
    " Node Core purchase cost multiplier": " 节点 核心购买 成本乘数",
    " Node purchase cost multiplier": " 节点 购买 成本乘数",
    " Node RAM upgrade cost multiplier": " 节点 内存升级 成本乘数",
    " Node production multiplier": " 节点 生产 成本乘数",
    " Node level upgrade cost multiplier": " 节点 等级升级 成本乘数",
    "[travel agency]": "[旅行社]",
    "\/ sec": "\/ 秒",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Requires (.+) strength, (.+) defense, (.+) dexterity, (.+) agility, (.+) charisma$/, '需要 $1 力量，$2 防御，$3 灵巧，$4 敏捷，$5 魅力'],
    [/^Work(.+)in(.+)progress$/, '工作$1正在$2进行中'],
    [/^Command (.+) not found$/, '命令 $1 未找到'],
    [/^You've finished creating (.+)!$/, '您已经完成了 $1 的创建！'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^(.+)\[icarus microsystems\](.+)$/, '$1\[伊卡洛斯微系统\]$2'],
    [/^(.+)\[joe\'s guns\](.+)$/, '$1\[乔的枪\]$2'],
    [/^(.+)\[iron gym\](.+)$/, '$1\[铁之健身房\]$2'],
    [/^(.+)\[deltaone\](.+)$/, '$1\[三角龙\]$2'],
    [/^\[alpha ent.\](.+)$/, '\[阿尔法公司\]$1'],
    [/^\[cia\](.+)$/, '\[中央情报局\]$1'],
    [/^(.+)\[city hall\](.+)\[world stock exchange\]$/, '$1\[市政府\]$2\[世界证券交易所\]'],
    [/^(.+)\[nsa\]$/, '$1\[安全局\]'],
    [/^(.+)\[four sigma\]$/, '$1\[四西格玛\]'],
    [/^(.+)\[the slums\]$/, '$1\[贫民窟\]'],
    [/^(.+)\[carmichael sec.\]$/, '$1\[卡迈克尔山脉\]'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^\-\$([\d\.]+)$/, '\-\$ $1'],
    [/^\$([\d\.]+)$/, '\$ $1'],
    [/^\$([\d\.]+) $/, '\$ $1 '],
    [/^\-\$([\d\.]+)$/, '\-\$ $1'],
    [/^\-\$([\d\.]+)k$/, '\-\$ $1k'],
    [/^\-\$([\d\.]+)m$/, '\-\$ $1m'],
    [/^\$([\d\.]+)k$/, '\$ $1k'],
    [/^\$([\d\.]+)m$/, '\$ $1m'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) minutes ([\d\.,]+) seconds$/, '$1 分钟 $2 秒'],
    [/^([\d\.,]+) hours ([\d\.,]+) minutes ([\d\.,]+) seconds$/, '$1 小时 $2分钟 $3 秒'],
    [/^([\d\.,]+) charisma$/, '$1 魅力'],
    [/^([\d\.,]+) hacking$/, '$1 黑客'],
    [/^([\d\.,]+) agility$/, '$1 敏捷'],
    [/^([\d\.,]+) defense$/, '$1 防御'],
    [/^([\d\.,]+) City Hall$/, '$1 市政府'],
    [/^([\d\.,]+) dexterity$/, '$1 灵巧'],
    [/^([\d\.,]+) strength$/, '$1 力量'],
    [/^([\d\.,]+) reputation$/, '$1 名声'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Requires (.+) hacking$/, '需要 $1 黑客'],
    [/^Requires (.+) hacking, (.+) charisma$/, '需要 $1 黑客，$2 魅力'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);