/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Hacking": "黑客攻击",
    "Click on this to upgrade your Source-File -1!": "单击此按钮可升级您的源文件 -1！",
    "City": "城市",
    "Hacknet": "黑客网",
    "Options": "选项",
    "Loading Bitburner v": "加载 比特燃烧器",
    "Script Editor": "脚本编辑器",
    "SKIP TUTORIAL": "跳过教程",
    "Stats": "统计",
    "Terminal": "终端",
    "This tutorial will show you the basics of the game. You may skip the tutorial at any time.": "本教程将向您展示游戏的基础知识。 您可以随时跳过本教程。",
    "to temporarily hide this tutorial.": "暂时隐藏本教程。",
    "Travel": "旅行",
    "Tutorial": "教程",
    "Welcome to Bitburner, a cyberpunk-themed incremental RPG! The game takes place in a dark, dystopian future... The year is 2077...": "欢迎来到以赛博朋克为主题的增量 RPG 游戏 比特燃烧器！ 游戏发生在一个黑暗、反乌托邦的未来……那一年是 2077 年……",
    "World": "世界",
    "You can also click the eye symbol": "您也可以单击眼睛符号",
    ", your Hacknet Nodes generated": ", 你的 黑客网 节点生成",
    ". While you were offline, your scripts generated": ". 当您离线时，您的脚本会生成",
    "Active Scripts": "活动的脚本",
    "Character": "角色",
    "Help": "帮助",
    "Offline for": "离线了 ",
    "reputation divided amongst your factions.": "声望在你的派系之间分配。",
    "and you gained": "并且你获得了",
    "net": "网络",
    "MAX": "最大",
    "Misc": "杂项",
    "Multipliers": "乘数",
    "Production": "生产",
    "The Hacknet is a global, decentralized network of machines. It is used by hackers all around the world to anonymously share computing power and perform distributed cyberattacks without the fear of being traced.": "黑客网 是一个全球性的、去中心化的机器网络。 世界各地的黑客都使用它来匿名共享计算能力并执行分布式网络攻击，而无需担心被追踪。",
    "Total Time played": "总游戏时长",
    "Travel Agency": "旅行社",
    "Time played since last Augmentation": "自上次增强以来的游戏时间",
    "Purchase Hacknet Node - ": "购买 黑客网 节点 -",
    "Node": "节点",
    "Nodes": "节点",
    "Current City": "当前城市",
    "Crime success multiplier": "犯罪成功乘数",
    "Crime money multiplier": "犯罪金钱乘数",
    "Company reputation gain multiplier": "公司声誉增益倍数",
    "exp": "经验值",
    "Faction reputation gain multiplier": "阵营声望增益乘数",
    "Game Saved!": "游戏已保存！",
    "General": "常规",
    "Here, you can purchase a Hacknet Node, a specialized machine that can connect and contribute its resources to the Hacknet network. This allows you to take a small percentage of profits from hacks performed on the network. Essentially, you are renting out your Node's computing power.": "在这里，您可以购买 黑客网 节点，这是一种可以连接 黑客网 网络并将其资源贡献给 黑客网 网络的专用机器。 这使您可以从网络上执行的黑客攻击中获得一小部分利润。 本质上，您是在出租 节点 的计算能力。",
    "Each Hacknet Node you purchase will passively earn you money. Each Hacknet Node can be upgraded in order to increase its computing power and thereby increase the profit you earn from it.": "您购买的每个 黑客网 节点都会被动地为您赚钱。 每个 黑客网 节点都可以升级以提高其计算能力，从而增加您从中获得的利润。",
    "ing": "",
    "Use \"nano [File Name]\" in the terminal to open files": "在终端中使用\"nano [文件名]\"打开文件",
    "Total Hacknet": "总黑客网",
    "Save & Close (Ctrl/Cmd + s": "保存 & 关闭 (Ctrl/Cmd + s",
    "Salary multiplier": "工资乘数",
    "Documentation": "文档",
    "From here, you can travel to any other city! A ticket costs": "从这里，您可以前往任何其他城市！ 一张票的费用",
    "Full": "满了",
    "Loading script editor!": "加载脚本编辑器！",
    "No open files": "没有打开文件",
    "Theme editor": "主题编辑器",
    "Terminal capacity": "终端容量",
    "Suppress travel confirmations": "禁止 旅行确认",
    "Suppress story messages": "禁止 故事 消息",
    "Suppress Saved Game Toast": "禁止 保存游戏 提示",
    "Suppress faction invites": "禁止 阵营邀请",
    "Suppress augmentations confirmation": "禁止 增强确认",
    "Suppress TIX messages": "禁止 TIX 消息",
    "Save Game": "保存游戏",
    "Save game on file save": "在文件保存时保存游戏",
    "Report bug": "报告Bug",
    "Soft Reset": "软重置",
    "Disable text effects": "禁用文本效果",
    "Disable hotkeys": "禁用快捷键",
    "Disable ascii art": "禁用ASCII艺术",
    "Diagnose files": "文件诊断",
    "Delete Game": "删除存档",
    "Netscript exec time (ms": "网络脚本 执行时间（毫秒",
    "Netscript log size": "网络脚本日志大小",
    "Netscript port size": "网络脚本端口大小",
    "The maximum number of entries that can be written to a the terminal. Setting this too high can cause the game to use a lot of memory.": "可以写入终端的最大条目数。 将此值设置得太高会导致游戏使用大量内存。",
    "The time (in seconds) between each autosave. Set to 0 to disable autosave.": "每次自动保存之间的时间（以秒为单位）。 设置为 0 以禁用自动保存。",
    "Apply for Agent Job": "申请代理工作",
    "Apply for IT Job": "申请IT工作",
    "Apply for Security Job": "申请保安工作",
    "Apply for Software Job": "申请软件工作",
    "Central Intelligence Agency": "中央情报局",
    "Requires": "需要",
    "Return to World": "返回到世界",
    "Let's start by heading to the Stats page. Click": "让我们首先前往统计页面。 点击",
    "on the main navigation menu (left-hand side of the screen": "在主导航菜单（屏幕左侧）",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "options": "选项",
    "home": "home",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Hacking": "黑客攻击",
    "Hacknet": "黑客网",
    "Hack": "黑客",
    "Money": "钱",
    "Defense": "防御",
    "Def": "防御",
    "HP": "生命值",
    "Strength": "力量",
    "Str": "力量",
    "Agility": "敏捷",
    "Agi": "敏捷",
    "Dexterity": "灵巧",
    "Dex": "灵巧",
    "Changelog": "更新日志",
    "Character": "角色",
    "Charisma": "魅力",
    "Cha": "魅力",
    "Bitburner v": "比特燃烧器 v",
    "Servers owned: ": "拥有的服务器：",
    "Augmentations installed: ": "增强已安装：",
    "Timestamp format:": "时间戳格式：",
    "Locale": "语言",
    " Nodes owned:": " 拥有的节点：",
    " [hospital]": " [医院]",
    " [megacorp]": " [大型企业]",
    "[foodnstuff]": "[食品]",
    "[powerhouse gym]": "[强力健身房]",
    "[rothman university]": "[罗斯曼大学]",
    "[universal energy]": "[宇宙能量]",
    "Sector-": "扇区-",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    " Chance multiplier": " 几率乘数",
    " Experience multiplier": " 经验乘数",
    " Level multiplier": " 等级乘数",
    " Speed multiplier": " 速度乘数",
    " Money multiplier": " 金钱乘数",
    " Growth multiplier": " 成长乘数",
    " Node Core purchase cost multiplier": " 节点 核心购买 成本乘数",
    " Node purchase cost multiplier": " 节点 购买 成本乘数",
    " Node RAM upgrade cost multiplier": " 节点 内存升级 成本乘数",
    " Node production multiplier": " 节点 生产 成本乘数",
    " Node level upgrade cost multiplier": " 节点 等级升级 成本乘数",
    "[travel agency]": "[旅行社]",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) minutes ([\d\.,]+) seconds$/, '$1 分钟 $2 秒'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);