/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Hacking": "黑客攻击",
    "Click on this to upgrade your Source-File -1!": "单击此按钮可升级您的源文件 -1！",
    "City": "城市",
    "Hacknet": "黑客网",
    "Options": "选项",
    "Loading Bitburner v": "加载 比特燃烧器",
    "Script Editor": "脚本编辑器",
    "SKIP TUTORIAL": "跳过教程",
    "Stats": "统计",
    "Terminal": "终端",
    "This tutorial will show you the basics of the game. You may skip the tutorial at any time.": "本教程将向您展示游戏的基础知识。 您可以随时跳过本教程。",
    "to temporarily hide this tutorial.": "暂时隐藏本教程。",
    "Travel": "旅行",
    "Tutorial": "教程",
    "Welcome to Bitburner, a cyberpunk-themed incremental RPG! The game takes place in a dark, dystopian future... The year is 2077...": "欢迎来到以赛博朋克为主题的增量 RPG 游戏 比特燃烧器！ 游戏发生在一个黑暗、反乌托邦的未来……那一年是 2077 年……",
    "World": "世界",
    "You can also click the eye symbol": "您也可以单击眼睛符号",
    ", your Hacknet Nodes generated": ", 你的 黑客网 节点生成",
    ". While you were offline, your scripts generated": ". 当您离线时，您的脚本会生成",
    "Active Scripts": "活动的脚本",
    "Character": "角色",
    "Help": "帮助",
    "Offline for": "离线了 ",
    "reputation divided amongst your factions.": "声望在你的派系之间分配。",
    "and you gained": "并且你获得了",
    "net": "网络",
    "MAX": "最大",
    "Misc": "杂项",
    "Multipliers": "乘数",
    "Production": "生产",
    "The Hacknet is a global, decentralized network of machines. It is used by hackers all around the world to anonymously share computing power and perform distributed cyberattacks without the fear of being traced.": "黑客网 是一个全球性的、去中心化的机器网络。 世界各地的黑客都使用它来匿名共享计算能力并执行分布式网络攻击，而无需担心被追踪。",
    "Total Time played": "总游戏时长",
    "Travel Agency": "旅行社",
    "Time played since last Augmentation": "自上次增强以来的游戏时间",
    "Node": "节点",
    "Nodes": "节点",
    "Current City": "当前城市",
    "Crime success multiplier": "犯罪成功乘数",
    "Crime money multiplier": "犯罪金钱乘数",
    "Company reputation gain multiplier": "公司声誉增益倍数",
    "exp": "经验值",
    "Faction reputation gain multiplier": "派系声望增益乘数",
    "Game Saved!": "游戏已保存！",
    "General": "常规",
    "Here, you can purchase a Hacknet Node, a specialized machine that can connect and contribute its resources to the Hacknet network. This allows you to take a small percentage of profits from hacks performed on the network. Essentially, you are renting out your Node's computing power.": "在这里，您可以购买 黑客网 节点，这是一种可以连接 黑客网 网络并将其资源贡献给 黑客网 网络的专用机器。 这使您可以从网络上执行的黑客攻击中获得一小部分利润。 本质上，您是在出租 节点 的计算能力。",
    "Each Hacknet Node you purchase will passively earn you money. Each Hacknet Node can be upgraded in order to increase its computing power and thereby increase the profit you earn from it.": "您购买的每个 黑客网 节点都会被动地为您赚钱。 每个 黑客网 节点都可以升级以提高其计算能力，从而增加您从中获得的利润。",
    "ing": "",
    "Use \"nano [File Name]\" in the terminal to open files": "在终端中使用\"nano [文件名]\"打开文件",
    "Total Hacknet": "总黑客网",
    "Save & Close (Ctrl/Cmd + s": "保存 & 关闭 (Ctrl/Cmd + s",
    "Salary multiplier": "工资乘数",
    "Documentation": "文档",
    "From here, you can travel to any other city! A ticket costs": "从这里，您可以前往任何其他城市！ 一张票的费用",
    "Full": "完整",
    "Loading script editor!": "加载脚本编辑器！",
    "No open files": "没有打开文件",
    "Theme editor": "主题编辑器",
    "Terminal capacity": "终端容量",
    "Suppress travel confirmations": "禁止 旅行确认",
    "Suppress story messages": "禁止 故事 消息",
    "Suppress Saved Game Toast": "禁止 保存游戏 提示",
    "Suppress faction invites": "禁止 派系邀请",
    "Suppress augmentations confirmation": "禁止 增强确认",
    "Suppress TIX messages": "禁止 TIX 消息",
    "Save Game": "保存游戏",
    "Save game on file save": "在文件保存时保存游戏",
    "Report bug": "报告Bug",
    "Soft Reset": "软重置",
    "Disable text effects": "禁用文本效果",
    "Disable hotkeys": "禁用快捷键",
    "Disable ascii art": "禁用ASCII艺术",
    "Diagnose files": "文件诊断",
    "Delete Game": "删除存档",
    "Netscript exec time (ms": "网络脚本 执行时间（毫秒",
    "Netscript log size": "网络脚本日志大小",
    "Netscript port size": "网络脚本端口大小",
    "The maximum number of entries that can be written to a the terminal. Setting this too high can cause the game to use a lot of memory.": "可以写入终端的最大条目数。 将此值设置得太高会导致游戏使用大量内存。",
    "The time (in seconds) between each autosave. Set to 0 to disable autosave.": "每次自动保存之间的时间（以秒为单位）。 设置为 0 以禁用自动保存。",
    "Apply for Agent Job": "申请代理工作",
    "Apply for IT Job": "申请IT工作",
    "Apply for Security Job": "申请保安工作",
    "Apply for Software Job": "申请软件工作",
    "Requires": "需要",
    "Return to World": "返回到世界",
    "Let's start by heading to the Stats page. Click": "让我们首先前往统计页面。 点击",
    "on the main navigation menu (left-hand side of the screen": "在主导航菜单（屏幕左侧）",
    "Beautify": "格式化",
    "Enter to Rename, ⇧Enter to Preview": "回车重命名，⇧回车预览",
    "Press space bar to start a drag.\n  When dragging you can use the arrow keys to move the item around and escape to cancel.\n  Some screen readers may require you to be in focus mode or to use your pass through key": "按空格键开始拖动。\n 拖动时，您可以使用箭头键移动项目并退出以取消。\n 某些屏幕阅读器可能要求您处于焦点模式或使用传递键",
    "Recent": "最近",
    "Rows per page": "每页行数",
    "This page displays a list of all of your scripts that are currently running across every machine. It also provides information about each script's production. The scripts are categorized by the hostname of the servers on which they are running.": "此页面显示当前在每台机器上运行的所有脚本的列表。 它还提供有关每个脚本制作的信息。 脚本按运行它们的服务器的主机名分类。",
    "Total production since last Augment Installation": "自上次安装以来的总产量",
    "Active": "活动中",
    "Apply for Business Job": "申请商务工作",
    "Apply to be a part-time Employee": "申请成为兼职员工",
    "Apply to be an Employee": "申请成为员工",
    "Basic": "基础",
    "Get treatment for wounds -": "接受伤口治疗 —",
    "Infiltrate Company": "渗透公司",
    "Total": "总计",
    "Train Agility (": "训练 敏捷 (",
    "Train Defense (": "训练 防御 (",
    "Train Dexterity (": "训练 灵巧 (",
    "Train Strength (": "训练 力量 (",
    " earned since you last installed Augmentations": "自您上次安装 增强 以来赚取的收入",
    "Welcome to the World Stock Exchange (WSE)!": "欢迎来到 世界证券交易所（WSE）！",
    "Aevum": "艾维姆",
    "Buy 4S Market Data TIX API Access - ": "购买 4S 市场数据 贸易信息交换(TIX) API 访问权限 - ",
    "Buy 4S Market Data Access - ": "购买4S市场数据访问权限 - ",
    "Buy Trade Information eXchange (TIX) API Access - ": "购买 贸易信息交换(TIX) API 访问权限 - ",
    "Buy WSE Account - ": "购买 世界证券交易所（WSE） 账户 - ",
    "Chongqing": "重庆",
    "commission fee.": "佣金费。",
    "Commission Fees: Every transaction you make has a": "佣金费用：您进行的每笔交易都有一个",
    "Four Sigma (4S) Market Data Feed": "四西格码 (4S) 市场数据馈送",
    "Four Sigma's (4S) Market Data Feed provides information about stocks that will help your trading strategies.": "四西格码 (4S) 市场数据馈送提供有助于您的交易策略的股票信息。",
    "Investopedia": "投资百科",
    "New Tokyo": "新东京",
    "Ishima": "伊岛",
    "TIX, short for Trade Information eXchange, is the communications protocol used by the WSE. Purchasing access to the TIX API lets you write code to create your own algorithmic/automated trading strategies.": "TIX 是 贸易信息交换 的缩写，是 世界证券交易所（WSE） 使用的通信协议。 通过购买 贸易信息交换(TIX) API 访问权限，您可以编写代码来创建自己的算法/自动交易策略。",
    "To begin trading, you must first purchase an account": "要开始交易，您必须先购买一个账户",
    "Trade Information eXchange (TIX) API": "贸易信息交换 (TIX) API",
    "Volhaven": "沃尔黑文",
    "WARNING: When you reset after installing Augmentations, the Stock Market is reset. You will retain your WSE Account, access to the TIX API, and 4S Market Data access. However, all of your stock positions are lost, so make sure to sell your stocks before installing Augmentations!": "警告：当您在安装 增强 后重置时，股票市场将被重置。 您将保留您的 世界证券交易所（WSE） 帐户、对 贸易信息交换 (TIX) API 的访问权限和 4S 市场数据访问权限。 但是，您的所有股票头寸都将丢失，因此请确保在安装增强功能之前卖出您的股票！",
    "Augmentations": "增强",
    "Companies": "公司",
    "Complete list of functions": "完整的功能列表",
    "Donate blood!": "献血！",
    "Enable bash hotkeys": "启用 bash 快捷键",
    "export": "导出",
    "Factions": "派系",
    "Force kill all active scripts": "强制杀掉所有活动的脚本",
    "Forcefully kill all active running scripts, in case there is a bug or some unexpected issue with the game. After using this, save the game and then reload the page. This is different then normal kill in that normal kill will tell the script to shut down while force kill just removes the references to it (and it should crash on it's own). This will not remove the files on your computer. Just forcefully kill all running instance of all scripts.": "强行杀掉所有正在运行的脚本，以防游戏出现错误或一些意外问题。 使用后，保存游戏，然后重新加载页面。 这与正常终止不同，正常终止会告诉脚本关闭，而强制终止只是删除对它的引用（并且它应该自行崩溃）。 这不会删除您计算机上的文件。 只需强行杀死所有脚本的所有正在运行的实例。",
    "Gain root access on CSEC": "获得 CSEC 的 root 访问权限",
    "Getting Started": "入门",
    "hydroflame (Current maintainer": "水焰 (当前维护者",
    "If this is set all ASCII art will be disabled.": "如果设置了此项，则所有 ASCII 艺术作品都将被禁用。",
    "If this is set, text effects will not be displayed. This can help if text is difficult to read in certain areas.": "如果设置了此项，则不会显示文本效果。 如果文本在某些区域难以阅读，这会有所帮助。",
    "Improved Bash emulation mode. Setting this to 1 enables several new Terminal shortcuts and features that more closely resemble a real Bash-style shell. Note that when this mode is enabled, the default browser shortcuts are overriden by the new Bash shortcuts.": "改进的 Bash 仿真模式。 将此设置为 1 会启用几个新的终端快捷方式和功能，它们更类似于真正的 Bash 风格的 shell。 请注意，启用此模式后，默认浏览器快捷方式将被新的 Bash 快捷方式覆盖。",
    "If this is set, the confirmation message before buying augmentation will not show up.": "如果设置，则不会显示购买增强前的确认消息。",
    "If this is set, the confirmation message before traveling will not show up. You will automatically be deducted the travel cost as soon as you click.": "如果设置了此项，则不会显示出行前的确认信息。您将在您点击后自动扣除差旅费用。",
    "If this is set, the stock market will never create any popup.": "如果设置了这个，股票市场将永远不会创建任何弹出窗口。",
    "If this is set, then any faction invites you receive will not appear as popups on the screen. Your outstanding faction invites can be viewed in the 'Factions' page.": "如果设置了这一点，那么您收到的任何派系邀请都不会在屏幕上显示为弹出窗口。您可以在“派系”页面中查看您出色的派系邀请。",
    "If this is set, then any messages you receive will not appear as popups on the screen. They will still get sent to your home computer as '.msg' files and can be viewed with the 'cat' Terminal command.": "如果已设置，则您收到的任何消息都不会在屏幕上显示为弹出窗口。它们仍会作为“.msg”文件发送到您的家用计算机，并且可以使用“cat”终端命令进行查看。",
    "If this is set, then most hotkeys (keyboard shortcuts) in the game are disabled. This includes Terminal commands, hotkeys to navigate between different parts of the game, and the \"Save and Close (Ctrl + b)\" hotkey in the Text Editor.": "如果设置了此项，则游戏中的大多数热键（键盘快捷键）将被禁用。这包括终端命令、在游戏不同部分之间导航的热键，以及文本编辑器中的“保存并关闭 (Ctrl + b)\”热键。",
    "If this is set, there will be no \"Saved Game\" toast appearing after save.": "如果设置了此项，保存后将不会出现“已保存的游戏”吐司。",
    "If your save file is extremely big you can use this button to view a map of all the files on every server. Be careful there might be spoilers.": "如果您的保存文件非常大，您可以使用此按钮查看每台服务器上所有文件的地图。小心可能有剧透。",
    "import": "进口",
    "Incremental game plaza": "增量游戏广场",
    "Infiltration": "渗透",
    "Keyboard Shortcuts": "键盘快捷键",
    "Milestones don't reward you for completing them. They are here to guide you if you're lost. They will reset when you install Augmentations.": "里程碑不会奖励您完成它们。如果您迷路了，他们会在这里为您提供指导。当您安装增强功能时，它们将重置。",
    "Netscript Programming Language": "网络脚本 编程语言",
    "NS1 vs NS2 (or .script vs .js": "NS1 与 NS2（或 .script 与 .js",
    "Perform a soft reset. Resets everything as if you had just purchased an Augmentation.": "执行软复位。重置所有内容，就像您刚刚购买了增强功能一样。",
    "Save your game any time a file is saved in the script editor.": "在脚本编辑器中保存文件时，随时保存您的游戏。",
    "Scripts": "脚本",
    "Servers & Networking": "服务器和网络",
    "Simplified list of functions": "简化的功能列表",
    "Soft reset and Restart tutorial": "软复位和重启教程",
    "Terminal commands and log entries will be timestamped. See https://date-fns.org/docs/Getting-Started/": "终端命令和日志条目将带有时间戳。见 https://date-fns.org/docs/Getting-Started/",
    "The maximum number of entries that can be written to a port using Netscript's write() function. Setting this too high can cause the game to use a lot of memory.": "可以使用 网络脚本 的 write() 函数写入端口的最大条目数。将此值设置得太高会导致游戏使用大量内存。",
    "The maximum number of lines a script's logs can hold. Setting this too high can cause the game to use a lot of memory if you have many scripts running.": "脚本日志可以容纳的最大行数。如果您有许多脚本在运行，则将此值设置得太高会导致游戏使用大量内存。",
    "The minimum number of milliseconds it takes to execute an operation in Netscript. Setting this too low can result in poor performance if you have many scripts running.": "在 网络脚本 中执行操作所需的最小毫秒数。如果您有许多脚本正在运行，则将此值设置得太低会导致性能不佳。",
    "This will reset all your stats to 1 and money to 1k. Are you sure?": "这会将您的所有统计数据重置为 1，将金钱重置为 1k。你确定吗？",
    "Timestamp format: ": "时间戳格式：",
    "Traveling": "旅行",
    "Tutorial / Documentation": "教程/文档",
    "Level": "等级",
    "Cores": "核心",
    "RAM": "内存",
    "Cancel": "取消",
    "Difficulty": "困难",
    "Everything that uses arrow can also use WASD": "使用箭头的所有东西也可以使用 WASD",
    "Get Ready!": "准备好！",
    "Infiltrating": "渗透",
    "Infiltration is a series of short minigames that get progressively harder. You take damage for failing them. Reaching the maximum level rewards you with intel you can trade for money or reputation.": "渗透是一系列越来越难的短小游戏。 你会因为失败而受到伤害。 达到最高级别会奖励您可以交易金钱或声誉的情报。",
    "Maximum level": "最高级别",
    "MOTHERBOARD ROOT JUNKMAIL FORMAT": "主板根垃圾邮件格式",
    "No game require use of the mouse.": "没有游戏需要使用鼠标。",
    "Sometimes the rest of the keyboard is used.": "有时会使用键盘的其余部分。",
    "Spacebar is the default action/confirm button.": "空格键是默认的操作/确认按钮。",
    "The minigames you play are randomly selected. It might take you few tries to get used to them.": "您玩的小游戏是随机选择的。 您可能需要几次尝试才能习惯它们。",
    "Trivial    Normal        Hard    Impossible": "简单    正常        困难    噩梦",
    "Type it backward": "向后输入",
    "Warning: This location is too heavily guarded for your current stats, try training or finding an easier location.": "警告：对于您当前的统计数据，此位置戒备森严，请尝试训练或寻找更容易的位置。",
    "KILL": "杀掉",
    "Forcefully kill all running scripts? This will also save your game and reload the game.": "强行杀死所有正在运行的脚本？ 这也将保存您的游戏并重新加载游戏。",
    "Invalid path. Failed to change directories": "路径无效。 更改目录失败",
    "Apply for Software Consultant Job": "申请软件顾问工作",
    "Gain hacking experience!": "获得黑客经验！",
    "Icarus Microsystems": "伊卡洛斯微系统公司",
    "Powerhouse Gym": "强力健身房",
    "Rothman University": "罗斯曼大学",
    "Stop taking course": "停止学习",
    "Stop training at gym": "停止在健身房训练",
    "Study Computer Science (free": "学习计算机科学（免费",
    "studying Computer Science": "学习计算机科学",
    "Take Algorithms course (": "参加算法课程（",
    "Take Data Structures course (": "参加数据结构课程（",
    "Take Leadership course (": "参加领导力课程（",
    "Take Management course (": "参加管理课程（",
    "Take Networks course (": "参加网络课程（",
    "This has cost you": "这让你付出了代价",
    "training your strength at a gym": "在健身房锻炼你的力量",
    "Unforunately, you do not qualify for this position": "很遗憾，您不符合此职位的资格",
    "Universal Energy": "环球能源",
    "You have been": "你已经",
    "You have gained": "你获得了",
    "You may cancel at any time": "你可以随时取消",
    "for": "",
    "/ sec) agility exp": "/秒) 敏捷经验",
    "/ sec) charisma exp": "/秒) 魅力经验",
    "/ sec) defense exp": "/秒) 防御经验",
    "/ sec) dexterity exp": "/秒) 灵巧经验",
    "/ sec) hacking exp": "/秒) 黑客经验",
    "/ sec) strength exp": "/秒) 力量经验",
    "agility experience": "敏捷经验",
    "Assassinate (": "暗杀（",
    "Attempt to commit armed robbery on a high-end store": "企图在高档商店持械抢劫",
    "Attempt to mug a random person on the street": "试图在街上随意抢劫一个人",
    "Attempt to rob property from someone's house": "企图从某人的房子里抢劫财物",
    "Attempt to shoplift from a low-end retailer": "试图从低端零售商处入店行窃",
    "Bond Forgery (": "债券伪造（",
    "Cancel crime": "取消犯罪",
    "chance of success": "成功的机会",
    "charisma experience": "魅力经验",
    "Crime successful!": "犯罪成功！",
    "Deal Drugs (": "Du品交易 (",
    "defense experience": "防御经验",
    "dexterity experience": "灵巧经验",
    "Grand theft Auto (": "侠盗猎车手 （",
    "hacking experience": "黑客经验",
    "Heist (": "抢劫 (",
    "Homicide (": "凶杀案（",
    "Kidnap and Ransom (": "绑架和赎金（",
    "Larceny (": "盗窃 (",
    "Mug someone (": "抢劫某人(",
    "Rob store (": "抢劫商店（",
    "shoplift": "入店行窃",
    "Shoplift (": "入店行窃 (",
    "strength experience": "力量经验",
    "Time remaining": "剩余时间",
    "Traffick illegal Arms (": "贩卖非法武器（",
    "You are attempting to": "你正试图",
    "You gained": "你获得了",
    "Crime failed!": "犯罪失败！",
    "rob a store": "抢劫商店",
    "Attempt to assassinate a high-profile target": "企图暗杀一个备受瞩目的目标",
    "Attempt to commit grand theft auto": "企图实施侠盗猎车",
    "Attempt to deal drugs": "尝试贩毒",
    "Attempt to forge corporate bonds": "试图伪造公司债券",
    "Attempt to kidnap and ransom a high-profile-target": "企图绑架和勒索一个备受瞩目的目标",
    "Attempt to murder a random person on the street": "试图在街上随意谋杀一个人",
    "Attempt to pull off the ultimate heist": "尝试完成终极抢劫",
    "Attempt to smuggle illegal arms into the city": "企图将非法武器走私进城",
    "Remaining": "剩余",
    "Progress": "进度",
    "Gain charisma experience!": "获得魅力经验！",
    "Requires TIX API Access": "需要 TIX API 访问权限",
    "You are currently working as a": "您目前的工作是",
    "You have been working for": "你工作了 ",
    "You have earned": "你赚了",
    "You will automatically finish after working for 8 hours. You can cancel earlier if you wish, but you will only gain": "您将在工作 8 小时后自动完成。 如果您愿意，您可以提前取消，但您只会获得",
    "(Current Company Reputation": "（目前公司声誉",
    ") agility exp": ") 敏捷经验",
    ") charisma exp": ") 魅力经验",
    ") defense exp": ") 防御经验",
    ") dexterity exp": ") 灵巧经验",
    ") hacking exp": ") 黑客经验",
    ") reputation for this company": ") 这家公司的声誉",
    ") strength exp": ") 力量经验",
    "Company Favor": "公司青睐",
    "Company reputation": "公司声誉",
    "Congratulations, you are now employed at Joe's Guns": "恭喜你，你现在就职于 Joe's Guns",
    "Do something else simultaneously": "同时做其他事情",
    "Employee": "员工",
    "half": "一半",
    "Job": "工作",
    "Job Title": "职称",
    "of the reputation you've earned so far.": "您迄今为止所获得的声誉。",
    "Quit": "退出",
    "Stop Working": "停止工作",
    "Work": "工作",
    "mug someone": "抢劫某人",
    "Job you last worked": "你上次工作的职位",
    "Focus": "集中",
    "Employer at which you last worked": "您上次工作的雇主",
    "commit larceny": "盗窃",
    "All Employers": "所有雇主",
    "rep": "代理",
    "Part-time Employee": "兼职员工",
    "You will have": "你将会拥有",
    "company favor upon resetting after installing Augmentations": "安装 增强 后重置时公司青睐",
    "Congratulations, you are now employed at FoodNStuff": "恭喜你，你现在就职于 食品厂",
    "A stock's price forecast can change over time. This is also affected by volatility. The more volatile a stock is, the more its price forecast will change.": "股票的价格预测会随着时间而改变。 这也受到波动性的影响。 一只股票的波动性越大，其价格预测的变化就越大。",
    "Access to the 4S Market Data feed will display two additional pieces of information about each stock: Price Forecast & Volatility": "访问 4S 市场数据源将显示关于每只股票的两条额外信息：价格预测和波动率",
    "Price Forecast indicates the probability the stock has of increasing or decreasing. A '+' forecast means the stock has a higher chance of increasing than decreasing, and a '-' means the opposite. The number of '+/-' symbols is used to illustrate the magnitude of these probabilities. For example, '+++' means that the stock has a significantly higher chance of increasing than decreasing, while '+' means that the stock only has a slightly higher chance of increasing than decreasing.": "价格预测表示股票上涨或下跌的概率。 '+' 预测意味着该股票上涨的可能性大于下跌的可能性，而“-”则表示相反。 “+/-”符号的数量用于说明这些概率的大小。 例如，“+++”表示该股票上涨的机会明显高于下跌的机会，而“+”表示该股票的上涨机会仅略高于下跌的机会。",
    "Volatility represents the maximum percentage by which a stock's price can change every tick (a tick occurs every few seconds while the game is running).": "波动率表示股票价格每次变动的最大百分比（在游戏运行时每隔几秒发生一次变动）。",
    "taking a Data Structures course": "参加数据结构课程",
    "Upgrade 'home' cores (": "升级 “home” 核心（",
    "Upgrade 'home' RAM (": "升级 “home” 内存（",
    "A business man is yelling at a clerk. You should come back later.": "一个商人正在对一个职员大喊大叫。 你应该晚点回来。",
    "Purchase": "购买",
    "\"Cores increase the effectiveness of grow() and weaken() on 'home'\"": "\"核心增加了'home'上grow()和weak()的有效性\"",
    "\"More RAM means more scripts on 'home'\"": "\"更多的内存意味着'home'上可以运行更多脚本\"",
    "\"You can order bigger servers via scripts. We don't take custom orders in person.\"": "\"您可以通过脚本订购更大的服务器。我们不会亲自接受定制订单。\"",
    "of RAM for": "内存 花费",
    "Please enter the server hostname below": "请在下面输入服务器主机名",
    "Would you like to purchase a new server with": "您想购买新服务器拥有",
    "TOR Router - Purchased": "TOR 路由器 - 已购买",
    "Use the scan/scan-analyze commands to search for the dark web connection.": "使用 scan/scan-analyze 命令搜索暗网连接。",
    "You have purchased a TOR router!": "您购买了 TOR 路由器！",
    "You now have access to the dark web from your home computer.": "您现在可以从家用计算机访问暗网。",
    "I know you can sense it. I know you're searching for it. It's why you spend night after night at your computer.": "我知道你能感觉到。 我知道你正在寻找它。 这就是为什么你夜复一夜地在电脑前度过的原因。",
    "It's real, I've seen it. And I can help you find it. But not right now. You're not ready yet.": "这是真的，我见过。 我可以帮你找到它。 但不是现在。 你还没准备好。",
    "Message received from unknown sender": "收到来自未知发件人的邮件",
    "taking a Networks course": "学习网络课程",
    "The fl1ght.exe program was added to your home computer": "fl1ght.exe 程序已添加到您的家用计算机",
    "Use this program to track your progress": "使用此程序来跟踪您的进度",
    "% complete.": "% 已完成.",
    "Cancel work on creating program": "取消创建程序的工作",
    "Create program": "创建程序",
    "Create Program": "创建程序",
    "If you cancel, your work will be saved and you can come back to complete the program later.": "如果您取消，您的工作将被保存，您可以稍后回来完成程序。",
    "MegaCorp": "大型企业",
    "Soon you will be contacted by a hacking group known as CyberSec. They can help you with your search.": "很快，一个名为 赛博安全 的黑客组织将与您联系。 他们可以帮助您进行搜索。",
    "The program is": "该程序",
    "This page displays any programs that you are able to create. Writing the code for a program takes time, which can vary based on how complex the program is. If you are working on creating a program you can cancel at any time. Your progress will be saved and you can continue later.": "此页面显示您可以创建的所有程序。 为程序编写代码需要时间，具体时间会因程序的复杂程度而异。 如果您正在创建一个程序，您可以随时取消。 您的进度将被保存，您可以稍后继续。",
    "This program allows you to directly connect to other servers through the 'scan-analyze' command": "该程序允许您通过“scan-analyze”命令直接连接到其他服务器",
    "training your agility at a gym": "在健身房训练你的敏捷性",
    "training your defense at a gym": "在健身房训练你的防御",
    "training your dexterity at a gym": "在健身房训练你的灵巧",
    "You are currently working on coding": "您目前正在编写代码",
    "You should join them, garner their favor, and exploit them for their Augmentations. But do not trust them. They are not what they seem. No one is.": "您应该加入他们，赢得他们的青睐，并利用他们进行增强。 但不要相信他们。 他们不是他们看起来的那样。 没有人是。",
    " Nodes": " 节点",
    " Nodes Expenses": " 节点开支",
    "Class": "课程",
    "Company Work": "公司工作",
    "Crimes": "犯罪",
    "Other": "其它",
    "Hospitalization": "住院",
    "The new program can be found on your home computer.": "新程序可以在您的家用计算机上找到。",
    "taking an Algorithms course": "学习算法课程",
    "assassinate a high-profile target": "暗杀一个引人注目的目标",
    "commit grand theft auto": "犯下侠盗猎车手",
    "commit homicide": "谋杀",
    "Company favor increases the rate at which you earn reputation for this company by 1% per favor. Company favor is gained whenever you reset after installing Augmentations. The amount of favor you gain depends on how much reputation you have with the company.": "公司好感使您为该公司赢得声誉的速度提高 1%。 每当您在安装增强后重置时，都会获得公司青睐。 您获得的青睐程度取决于您在公司中的声誉。",
    "deal drugs": "Du品交易",
    "forge corporate bonds": "伪造公司债券",
    "kidnap someone for ransom": "绑架某人索要赎金",
    "pull off the ultimate heist": "完成终极抢劫",
    "taking an Algorithms course": "学习算法课程",
    "traffick illegal arms": "贩运非法武器",
    "But first, you must pass our test. Find and install the backdoor on our server.": "但首先，您必须通过我们的测试。 在我们的服务器上查找并安装后门。",
    "CyberSec": "赛博安全",
    "We've been watching you. Your skills are very impressive. But you're wasting your talents. If you join us, you can put your skills to good use and change the world for the better. If you join us, we can unlock your full potential.": "我们一直在看着你。 你的技能令人印象深刻。 但是你在浪费你的天赋。 如果您加入我们，您可以充分利用您的技能，让世界变得更美好。 如果您加入我们，我们可以释放您的全部潜力。",
    "This program executes a brute force attack that opens SSH ports": "这个程序执行蛮力攻击，打开SSH端口",
    "Netburners": "网络燃烧器",
    "Warning: Joining this faction may prevent you from joining other factions during this run!": "警告：加入此派系可能会阻止您在此轮游戏期间加入其他派系！",
    "Would you like to join": "你是否想加入",
    "You have received a faction invitation.": "你收到了一个派系邀请。",
    "Join!": "加入!",
    "Decide later": "迟点再决定",
    "This program is used to display hacking and Netscript-related information about servers": "该程序用于显示有关 服务器 的黑客和 网络脚本 相关信息",
    "Lists all factions you have joined": "列出你加入的所有派系",
    "Lists factions you have been invited to. You can accept these faction invitations at any time.": "列出您受邀加入的派系。 您可以随时接受这些派系邀请。",
    "Outstanding Faction Invitations": "杰出派系邀请",
    "This program allows you to use the scan-analyze command with a depth up to 5": "该程序允许您使用深度高达 5 的 扫描分析（scan-analyze）命令",
    "IT Intern": "T实习生",
    "Software Engineering Intern": "软件工程实习生",
    "Perform work/carry out assignments for your faction to help further its cause! By doing so you will earn reputation for your faction. You will also gain reputation passively over time, although at a very slow rate. Earning reputation will allow you to purchase Augmentations through this faction, which are powerful upgrades that enhance your abilities.": "为您的派系执行工作/执行任务，以帮助推动其事业！ 通过这样做，您将为您的派系赢得声望。 随着时间的推移，你也会被动地获得声望，尽管速度非常缓慢。 赢得声望将允许您通过该派系购买增强，这是增强您能力的强大升级。",
    "A device that is embedded in the back of the neck. The NeuroFlux Governor monitors and regulates nervous impulses coming to and from the spinal column, essentially 'governing' the body. By doing so, it improves the functionality of the body's nervous system.": "一种嵌入颈部后部的装置。 神经通量 调节器监测和调节进出脊柱的神经冲动，从根本上“控制”身体。 通过这样做，它可以改善身体神经系统的功能。",
    " Contracts": "合同",
    " Node Cache Architecture Neural-Upload": "节点缓存架构神经上传",
    " Node Core Direct-Neural Interface": "节点核心直接神经接口",
    " Node CPU Architecture Neural-Upload": "节点 CPU 架构神经上传",
    " Node Kernel Direct-Neural Interface": "节点内核直接神经接口",
    " Node NIC Architecture Neural-Upload": "节点网卡架构神经上传",
    ". Augmentations are powerful upgrades that will enhance your abilities.": ".增强是强大的升级，将增强您的能力。",
    ") reputation for this faction": ") 该派系的声望",
    "As your reputation with this faction rises, you will unlock Augmentations, which you can purchase to enhance your abilities.": "随着您在该派系中的声望提高，您将解锁增强功能，您可以购买它来增强您的能力。",
    "at": "在",
    "Back": "返回",
    "Buy": "购买",
    "carrying out hacking contracts": "执行黑客合约",
    "Complete hacking contracts for your faction. Your effectiveness, which determines how much reputation you gain for this faction, is based on your hacking skill. You will gain hacking exp.": "为你的派系完成黑客合同。您的效率决定了您为此派系获得的声望，这取决于您的黑客技能。您将获得黑客经验。",
    "Current Faction Reputation": "当前派系声誉",
    "Effects": "效果",
    "Faction Augmentations": "派系扩充",
    "Faction Favor": "派系青睐",
    "faction reputation": "派系声望",
    "Favor": "恩惠",
    "favor with": "赞成",
    "for your faction": "为你的派系",
    "hacknet nodes cost": "黑客网络节点成本",
    "hacknet nodes upgrade cost": "hacknet节点升级费用",
    "hacknet production": "黑客网络制作",
    "Installs a Direct-Neural Interface jack into the arm that is capable of connecting to a Hacknet Node. This lets the user access and manipulate the Node's kernel using electrochemical signals.": "将直接神经接口插孔安装到能够连接到 Hacknet 节点的手臂中。这让用户可以使用电化学信号访问和操纵节点的内核。",
    "Installs a Direct-Neural Interface jack into the arm that is capable of connecting to a Hacknet Node. This lets the user access and manipulate the Node's processing logic using electrochemical signals.": "将直接神经接口插孔安装到能够连接到 Hacknet 节点的手臂中。这让用户可以使用电化学信号访问和操纵节点的处理逻辑。",
    "Price multiplier: x": "价格乘数：x",
    "Purchase Augmentations": "购买增强",
    "Reputation": "声誉",
    "Sort by Cost": "按成本排序",
    "Sort by Default Order": "按默认顺序排序",
    "Sort by Purchasable": "按可购买的排序",
    "Sort by Reputation": "按声誉排序",
    "Stop Faction Work": "停止派系工作",
    "The price of every Augmentation increases for every queued Augmentation and it is reset when you install them.": "每次排队的扩充都会增加每个扩充的价格，并在您安装它们时重置。",
    "There is no penalty for cancelling earlier.": "提前取消不会有任何处罚。",
    "These are all of the Augmentations that are available to purchase from": "这些是可以从以下位置购买的所有增强",
    "This special augmentation can be leveled up infinitely. Each level of this augmentation increases ALL multipliers by 1%, stacking multiplicatively.": "这种特殊的增强可以无限升级。这种增强的每一级都将所有乘数增加 1%，以乘法叠加。",
    "Unlock donations at": "解锁捐款",
    "Uploads the architecture and design details of a Hacknet Node's CPU into the brain. This allows the user to engineer custom hardware and software  for the Hacknet Node that provides better performance.": "将 黑客网 节点的 CPU 的架构和设计细节上传到大脑中。这允许用户为提供更好性能的 Hacknet 节点设计自定义硬件和软件。",
    "Uploads the architecture and design details of a Hacknet Node's main-memory cache into the brain. This allows the user to engineer custom cache hardware for the  Hacknet Node that offers better performance.": "将 黑客网 节点的主内存缓存的架构和设计细节上传到大脑中。这允许用户为提供更好性能的 Hacknet 节点设计自定义缓存硬件。",
    "Uploads the architecture and design details of a Hacknet Node's Network Interface Card (NIC) into the brain. This allows the user to engineer a custom NIC for the Hacknet Node that offers better performance.": "将 黑客网 节点的网络接口卡 (NIC) 的架构和设计细节上传到大脑中。这允许用户为提供更好性能的 黑客网 节点设计自定义 NIC。",
    "You are currently": "您目前是",
    "You have been doing this for": "你一直在这样做",
    "You will automatically finish after working for 20 hours. You can cancel earlier if you wish.": "您将在工作 20 小时后自动完成。如果您愿意，可以提前取消。",
    "Backup your theme or share it with others by copying the string above.": "通过复制上面的字符串备份您的主题或与他人分享。",
    "button": "按钮",
    "Dark Blue": "深蓝",
    "disabled": "禁用",
    "disabled button": "禁用按钮",
    "Dracula": "德古拉",
    "error": "错误",
    "error button": "错误按钮",
    "Example tooltip": "示例工具提示",
    "Lets you view additional pricing and volatility information about stocks": "让您查看有关股票的其他定价和波动性信息",
    "money": "金钱",
    "Replace the current theme with a pre-built template using the buttons below.": "使用以下按钮将当前主题替换为预先构建的模板。",
    "Smooth Green": "柔滑的绿色",
    "success": "成功",
    "Warmer": "暖色",
    "warning": "警告",
    "Welcome to the file diagnostic! If your save file is really big it's likely because you have too many text/scripts. This tool can help you narrow down where they are.": "欢迎来到文件诊断！ 如果您的保存文件很大，很可能是因为您有太多的文本/脚本。 该工具可以帮助您缩小它们所在的位置。",
    "displays a list of all available Terminal commands, how to use them, and a description of what they do.": "显示所有可用终端命令的列表、如何使用它们以及它们的作用的描述。",
    "Don't forget to press Enter after typing the command": "输入命令后不要忘记按 回车键",
    "gives some more detailed information about servers on the network. Try it now!": "提供有关网络上服务器的一些更详细的信息。 现在就试试！",
    "Hostname        IP       Root Access": "主机名称        IP       Root访问权限",
    "is a basic command that shows files on the computer. Right now, it shows that you have a program called": "是显示计算机上文件的基本命令。 现在，它表明您有一个名为",
    "is used to interface with your home computer as well as all of the other machines around the world.": "用于与您的家用计算机以及世界各地的所有其他机器连接。",
    "Let's head to your computer's terminal by clicking": "让我们通过单击前往您的计算机终端",
    "Let's try another command. Enter": "让我们尝试另一个命令。 回车",
    "Let's try it out. Start by entering": "让我们试试看。 开始通过输入",
    "NUKE.exe on your computer. We'll get to what this does later.": "NUKE.exe 在您的计算机上。 稍后我们将了解它的作用。",
    "on the main navigation menu.": "在主导航菜单上。",
    "shows a lot of important information about your progress, such as your skills, money, and bonuses.": "显示许多关于您的进步的重要信息，例如您的技能、金钱和奖金。",
    "shows all available network connections. In other words, it displays a list of all servers that can be connected to from your current machine. A server is identified by its hostname.": "显示所有可用的网络连接。 换句话说，它显示了可以从您当前的机器连接到的所有服务器的列表。 服务器由其主机名标识。",
    "That's great and all, but there's so many servers. Which one should you go to?": "这很好，但是服务器太多了。 你应该去哪一个？",
    "Type 'help name' to learn more about the command": "输入“help name”以了解有关命令的更多信息",
    "Using your home computer's terminal, you can connect to other machines throughout the world. Let's do that now by first entering": "使用家用计算机的终端，您可以连接到世界各地的其他机器。 现在让我们先输入",
    "Really delete your game? (It's permanent!": "真的删除你的游戏进度？ （这是永久的！",
    "Confirm": "确认",
    "Closed": "已关闭",
    "NO": "否",
    "Try doing that now.": "现在尝试这样做。",
    "s & Networking": " & 联网",
    "You are now attempting to hack the server. Performing a hack takes time and only has a certain percentage chance of success. This time and success chance is determined by a variety of factors, including your hacking skill and the server's security level.": "您现在正试图入侵服务器。 执行 黑客 需要时间，并且只有一定百分比的成功机会。 此时间和成功机会由多种因素决定，包括您的黑客技能和服务器的安全级别。",
    "For this server, the required hacking skill is only 1, which means you can hack it right now. However, in order to hack a server you must first gain root access. The NUKE.exe program that we saw earlier on your home computer is a virus that will grant you root access to a machine if there are enough open ports.": "对于这台服务器，所需的黑客技能仅为1，这意味着您现在可以对其进行黑客攻击。 但是，为了破解服务器，您必须首先获得 root 访问权限。 我们之前在您的家用计算机上看到的 NUKE.exe 程序是一种病毒，如果有足够的开放端口，它将授予您对机器的 root 访问权限。",
    "This page contains a lot of different documentation about the game's content and mechanics. I know it's a lot, but I highly suggest you read (or at least skim) through this before you start playing . That's the end of the tutorial. Hope you enjoy the game!": "此页面包含许多关于游戏内容和机制的不同文档。 我知道很多，但我强烈建议你在开始玩之前通读（或至少略读）这个。 本教程到此结束。 希望你喜欢这款游戏！",
    "If you know even a little bit of programming it is highly recommended you use NS2 instead. You will enjoy the game much more. NS1 files end with .script and are a subset of javascript. NS2 files end with .js and are full speed native javascript.": "如果您知道一点点编程，强烈建议您改用 NS2。 你会更喜欢这个游戏。 NS1 文件以 .script 结尾，是 javascript 的一个子集。 NS2 文件以 .js 结尾，并且是全速原生 javascript。",
    "You are now connected to another machine! What can you do now? You can hack it!": "您现在已连接到另一台机器！你现在可以做什么？你可以破解它！",
    "You can learn more about the difference between them later in the documentation.": "您可以在后面的文档中详细了解它们之间的区别。",
    "You just purchased a Hacknet Node! This Hacknet Node will passively earn you money over time, both online and offline. When you get enough money, you can upgrade your newly-purchased Hacknet Node below.": "您刚刚购买了一个 黑客网 节点！随着时间的推移，这个 黑客网 节点将被动地为您赚钱，无论是在线还是离线。当您获得足够的钱时，您可以在下面升级您新购买的 黑客网 节点。",
    "You now have root access! You can hack the server using": "您现在拥有 root 访问权限！您可以使用",
    "Your script is now running! It will continuously run in the background and will automatically stop if the code ever completes (the n00dles.script will never complete because it runs an infinite loop).": "您的脚本现在正在运行！它会在后台持续运行，并且会在代码完成时自动停止（n00dles.script 永远不会完成，因为它运行一个无限循环）。",
    "If your attempt to hack the server is successful, you will steal a certain percentage of the server's total money. This percentage is affected by your hacking skill and the server's security level.": "如果您入侵服务器的尝试成功，您将窃取服务器总资金的一定比例。此百分比受您的黑客技能和服务器安全级别的影响。",
    "in the main navigation menu to look at the documentation.": "在主导航菜单中查看文档。",
    "In the year 2077, currency has become digital and decentralized. People and corporations store their money on servers and computers. Using your hacking abilities, you can hack servers to steal money and gain experience.": "在 2077 年，货币已经数字化和去中心化。人们和公司将他们的钱存储在服务器和计算机上。使用您的黑客能力，您可以入侵服务器以窃取金钱并获得经验。",
    "It is also possible to run scan-analyze with a higher depth. Let's try a depth of two with the following command": "也可以使用更高的深度运行扫描分析。让我们使用以下命令尝试深度为 2",
    "Kill": "杀",
    "Lastly, click on": "最后，点击",
    "Let's check out some statistics for our running scripts by clicking": "让我们通过单击查看我们正在运行的脚本的一些统计信息",
    "Let's go to": "让我们去",
    "Let's head home before creating our first script!": "在创建我们的第一个脚本之前，让我们回家吧！",
    "Now we'll run the script. Scripts require a certain amount of RAM to run, and can be run on any machine which you have root access to. Different servers have different amounts of RAM. You can also purchase more RAM for your home server.": "现在我们将运行脚本。脚本需要一定数量的 内存 才能运行，并且可以在您具有 root 访问权限的任何机器上运行。不同的服务器有不同数量的 内存。您还可以为您的家庭服务器购买更多 内存。",
    "Now you can see information about all servers that are up to two nodes away, as well as figure out how to navigate to those servers through the network. You can only connect to a server that is one node away. To connect to a machine, use": "现在，您可以查看距离最多两个节点的所有服务器的信息，并了解如何通过网络导航到这些服务器。您只能连接到一个节点之外的服务器。要连接到机器，请使用",
    "NUKE successful! Gained root access to n00dles": "NUKE成功！获得对 n00dles 的 root 访问权限",
    "One last thing about scripts, each active script contains logs that detail what it's doing. We can check these logs using the tail command. Do that now for the script we just ran by typing": "关于脚本的最后一件事，每个活动脚本都包含详细说明其正在执行的操作的日志。我们可以使用 tail 命令检查这些日志。现在为我们刚刚通过键入运行的脚本执行此操作",
    "Organization name: Noodle Bar": "机构名称：面吧",
    "Scripts must end with the .script extension. Let's make a script now by entering": "脚本必须以 .script 扩展名结尾。现在让我们通过输入来制作脚本",
    "shows more detailed information about each server that you can connect to (servers that are a distance of one node away).": "显示有关您可以连接的每台服务器（距离一个节点的距离的服务器）的更多详细信息。",
    "shows that there do not need to be any open ports on this machine for the NUKE virus to work, so go ahead and run the virus using": "显示不需要在这台机器上打开任何端口来让 NUKE 病毒工作，所以继续运行病毒",
    "The amount of money on a server is not limitless. So, if you constantly hack a server and deplete its money, then you will encounter diminishing returns in your hacking. You will need to use": "服务器上的钱不是无限的。因此，如果您不断地入侵服务器并耗尽其资金，那么您的入侵行为将导致收益递减。您将需要使用",
    "The log for this script won't show much right now (it might show nothing at all) because it just started running...but check back again in a few minutes!": "这个脚本的日志现在不会显示太多（它可能什么都不显示），因为它刚刚开始运行......但几分钟后再回来查看！",
    "These scripts can passively earn you income and hacking experience. Your scripts will also earn money and experience while you are offline, although at a slightly slower rate.": "这些脚本可以被动地为您赚取收入和黑客经验。您的脚本也会在您离线时赚取金钱和经验，但速度会稍慢一些。",
    "This covers the basics of hacking. To learn more about writing scripts, select": "这涵盖了黑客攻击的基础知识。要了解有关编写脚本的更多信息，请选择",
    "This is the script editor. You can use it to program your scripts. Scripts are written in a simplified version of javascript. Copy and paste the following code into the script editor": "这是脚本编辑器。您可以使用它来编写脚本。脚本是用 javascript 的简化版本编写的。将以下代码复制并粘贴到脚本编辑器中",
    "This page displays information about all of your scripts that are running across every server. You can use this to gauge how well your scripts are doing. Let's go back to": "此页面显示有关在每个服务器上运行的所有脚本的信息。您可以使用它来衡量脚本的运行情况。让我们回到",
    "This page lists all of the different locations you can currently travel to. Each location has something that you can do. There's a lot of content out in the world, make sure you explore and discover!": "此页面列出了您目前可以前往的所有不同地点。每个位置都有您可以做的事情。世界上有很多内容，一定要探索和发现！",
    "through the main navigation menu now.": "现在通过主导航菜单。",
    "To check how much RAM is available on this machine, enter": "要检查这台机器上有多少可用的 RAM，请输入",
    "To create a new script or edit an existing one, you can use": "要创建新脚本或编辑现有脚本，您可以使用",
    "To save and close the script editor, press the button in the bottom left, or press ctrl + b.": "要保存并关闭脚本编辑器，请按左下角的按钮，或按 ctrl + b。",
    "we can see that the n00dles server is only one node away. Let's connect so it now using": "我们可以看到 n00dles 服务器距离只有一个节点。让我们连接它现在使用",
    "We have 8GB of free RAM on this machine, which is enough to run our script. Let's run our script using": "我们在这台机器上有 8GB 的​​空闲内存，足以运行我们的脚本。让我们运行我们的脚本",
    "which increases the speed of hack and grow.": "这增加了hack和grow的速度。",
    "which tricks the company into adding money to their server and": "这诱使公司向他们的服务器增加资金，并且",
    "after the hack command finishes running (Sidenote: Pressing ctrl + c will end a command like hack early": "在 hack 命令完成运行后（旁注：按 ctrl + c 将提前结束像 hack 这样的命令",
    "Analyzing system...": "分析系统...",
    "Available money on 'n00dles' grown by 1274.637970%. Gained 3.300 hacking exp.": "“n00dles”上的可用资金增长了 1274.637970%。获得 3.300 黑客经验。",
    "Bad command. Please follow the tutorial": "不好的命令。请按照教程",
    "Before you try to hack a server, you should run diagnostics using": "在您尝试破解服务器之前，您应该使用以下命令运行诊断程序",
    "finishes running it will show useful information about hacking the server.": "完成运行它将显示有关黑客服务器的有用信息。",
    "For anyone with basic programming experience, this code should be straightforward. This script will continuously hack the n00dles server.": "对于任何具有基本编程经验的人来说，这段代码应该很简单。此脚本将不断破解 n00dles 服务器。",
    "For now, let's move on to something else!": "现在，让我们继续做其他事情！",
    "From any server you can get back home using": "从任何服务器，您都可以使用",
    "From the results of": "从结果来看",
    "Here you can purchase new Hacknet Nodes and upgrade your existing ones. Let's purchase a new one now.": "在这里，您可以购买新的 黑客网 节点并升级现有的节点。我们现在买一个新的。",
    "Enable vim mode": "启用vim模式",
    "Font size": "字体大小",
    "light": "浅色",
    "dark": "深色",
    "Use whitespace over tabs": "使用空格代替Tab",
    "This program cracks open FTP ports": "这个程序破解开放的 FTP 端口",
    "Yes": "是",
    "No": "否",
    "AutoLink.exe lets you automatically connect to other servers when using 'scan-analyze'.": "AutoLink.exe 可让您在使用 “scan-analyze”（扫描分析） 时自动连接到其他服务器。",
    "DeepscanV1.exe lets you run 'scan-analyze' with a depth up to 5.": "DeepscanV1.exe 允许您运行深度高达 5 的“scan-analyze”（扫描分析）。",
    "No such (exe, script, js, ns, or cct) file! (Only programs that exist on your home computer or scripts on home can be run": "没有这样的（exe、script、js、ns 或 cct）文件！ （只能运行家用电脑上的程序或家用的脚本",
    "This executable cannot be run.": "无法运行此可执行文件。",
    "When using scan-analyze, click on a server's hostname to connect to it.": "使用 scan-analyze（扫描分析）时，单击服务器的主机名以连接到它。",
    "Must pass a server hostname or IP as an argument for ServerProfiler.exe": "必须将服务器主机名或 IP 作为参数传递给 ServerProfiler.exe",
    "You will automatically finish after working for 8 hours. You can cancel earlier if you wish, and there will be no penalty because this is a part-time job.": "您将在工作 8 小时后自动完成。 如果您愿意，您可以提前取消，并且不会受到任何处罚，因为这是一份兼职工作。",
    "Software Consultant": "软件顾问",
    "Do not try to save the world. There is no world to save. If you want to find the truth, worry only about yourself. Ethics and morals will get you killed.": "不要试图拯救世界。 没有世界可以拯救。 如果你想找到真相，只需要担心你自己。 道德和道德会让你丧命。",
    "Find and install the backdoor on our server. Then, we will contact you again.": "在我们的服务器上查找并安装后门。 然后，我们会再次与您联系。",
    "Join us, and people will fear you, too.": "加入我们，人们也会害怕你。",
    "NiteSec": "黑夜安保",
    "People say that the corrupted governments and corporations rule the world. Yes, maybe they do. But do you know who everyone really fears? People like us. Because they can't hide from us. Because they can't fight shadows and ideas with bullets.": "人们说腐败的政府和企业统治着世界。 是的，也许他们会。 但是你知道每个人真正害怕谁吗？ 像我们这样的人。 因为他们无法躲避我们。 因为他们无法用子弹对抗阴影和想法。",
    "Watch out for a hacking group known as NiteSec.": "提防名为 黑夜安保 的黑客组织。",
    "Carry out field missions for your faction. Your effectiveness, which determines how much reputation you gain for this faction, is based on all of your stats. You will gain exp for all stats.": "为你的派系执行实地任务。 您的效率决定了您为此派系获得的声望，它基于您的所有统计数据。 您将获得所有统计数据的经验值。",
    "faction favor after installing an Augmentation.": "安装增强后的派系支持。",
    "Faction favor increases the rate at which you earn reputation for this faction by 1% per favor. Faction favor is gained whenever you install an Augmentation. The amount of favor you gain depends on the total amount of reputation you earned with this faction. Across all resets.": "派系恩惠使您为该派系赢得声望的速度提高 1%。 每当您安装增强功能时，都会获得派系青睐。 您获得的好感度取决于您在该派系中获得的声望总量。 在所有重置中。",
    "Field Work": "实地工作",
    "Security Work": "安保工作",
    "Serve in a security detail for your faction. Your effectiveness, which determines how much reputation you gain for this faction, is based on your combat stats. You will gain exp for all combat stats.": "为您的派系提供安全细节。 你的效能决定了你为此派系获得的声望，它取决于你的战斗数据。 您将获得所有战斗数据的经验值。",
    "The City of the Future.": "未来之城。",
    "total faction reputation": "总派系声望",
    " skill": "技能",
    "A cochlear implant with an embedded computer that analyzes incoming speech. The embedded computer processes characteristics of incoming speech, such as tone and inflection, to pick up on subtle cues and aid in social interactions.": "带有分析传入语音的嵌入式计算机的人工耳蜗。嵌入式计算机处理传入语音的特征，例如语气和语调，以获取微妙的线索并协助社交互动。",
    "A collection of digital assets saved on a small chip. The chip is implanted into your wrist. A small jack in the chip allows you to connect it to a computer and upload the assets.": "保存在小芯片上的数字资产集合。芯片被植入你的手腕。芯片中的一个小插孔允许您将其连接到计算机并上传资产。",
    "A cranial implant that intelligently stimulates certain areas of the brain in order to improve cognitive functions.": "一种颅骨植入物，可以智能地刺激大脑的某些区域，以改善认知功能。",
    "A cranial implant that is embedded within the inner ear structures and optic nerves. It regulates and enhances balance and hand-eye coordination.": "一种嵌入内耳结构和视神经内的颅骨植入物。它调节和增强平衡和手眼协调能力。",
    "after installing Augmentations.": "安装增强后。",
    "agility skill": "敏捷技能",
    "carrying out field missions": "执行外地任务",
    "CashRoot Starter Kit": "CashRoot 入门套件",
    "dexterity skill": "灵巧技能",
    "faster hack(), grow(), and weaken(": "更快的hack()、grow()和weak(",
    "hack() success chance": "hack() 成功几率",
    "hacking exp": "黑客经验",
    "Neuralstimulator": "神经刺激器",
    "performing security detail": "执行安全细节",
    "Speech Processor Implant": "语音处理器植入",
    "Start with": "开始于",
    "Synthetic nerve-enhancements are injected into all major parts of the somatic nervous system, supercharging the spread of neural signals and increasing reflex speed.": "合成神经增强剂被注入躯体神经系统的所有主要部分，增强神经信号的传播并提高反射速度。",
    "This upgraded version of the 'Augmented Targeting' implant is capable of augmenting reality by digitally displaying weaknesses and vital signs of threats.": "这种“增强瞄准”植入物的升级版本能够通过数字显示威胁的弱点和生命体征来增强现实。",
    "Wired Reflexes": "有线反射",
    "\\(\\huge{r = \\text{total faction reputation}}\\": "\\(\\huge{r = \\text{总派系声誉}}\\",
    "\\(\\huge{r = reputation}\\": "\\(\\huge{r = 声誉}\\",
    "A decrepit altar stands in the middle of a dilapidated church.": "一座破旧的教堂中间矗立着一座破旧的祭坛。",
    "A symbol is carved in the altar.": "祭坛上雕刻着一个符号。",
    "Would you like to travel to": "你想旅行前往 ",
    "Church of the Machine God": "机神教会",
    "? The trip will cost": " 吗? 旅行将会花费 ",
    "Business Intern": "商务实习生",
    "cores": "核心",
    "You are now in": "你现在在 ",
    "Spin!": "转动！",
    "Stop playing": "不玩了",
    "Tail!": "反面！",
    "Head!": "正面！",
    "waiting": "等待",
    "won": "赢了",
    "Black": "黑",
    "Comm": "普通",
    "DefComm": "不同寻常",
    "Even": "双",
    "High": "高",
    "lost": "输了",
    "Low": "低",
    "Odd": "单",
    "Pay lines": "支付线",
    "Play blackjack": "玩二十一点",
    "Play coin flip": "玩硬币翻转",
    "Play roulette": "玩轮盘赌",
    "Play slots": "玩老虎机",
    "playing": "游戏中",
    "Red": "红",
    "Result": "结果",
    "Rho Construction": "建筑工程",
    "win!": "赢了!",
//    "T": "反面",
//    "H": "正面",
    "lose!": "输了!",
    "You lost!": "你输了!",
    "You won!": "你赢了!",
    "You Won! Blackjack!": "你赢了！二十一点！",
    "Count": "总数",
    "Dealer": "庄",
    "Player": "玩家",
    "or": " 或 ",
    "Stay": "开牌",
    "Total earnings this session": "本期总收入",
    "Wager (Max": "下注（最大",
    "Must bet a postive amount": "必须得到一个正数",
    "Push! (Tie": "和! (平局",
    "Hit": "发牌",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Aevum Police Headquarters": "艾维姆警察总部",
    "AeroCorp": "航空公司",
    "Omega Software": "欧米茄软件",
    "Nova Medical": "新医疗",
    "NetLink Technologies": "网联科技",
    "Iker Molina Casino": "伊克尔莫利纳赌场",
    "Galactic Cybersystems": "银河网络系统",
    "Fulcrum Technologies": "支点科技",
    "ECorp": "环保公司",
    "Crush Fitness Gym": "粉碎健身馆",
    "Clarke Incorporated": "克拉克公司",
    "Bachman & Associates": "巴赫曼公司",
    "Watchdog Security": "看门狗安保",
    "Summit University": "萨米特大学",
    "Storm Technologies": "风暴科技",
    "Snap Fitness Gym": "Snap 健身馆",
    "ZB Institute of Technology": "中宝工学院",
    "SysCore Securities": "SysCore Securities",
    "OmniTek Incorporated": "OmniTek 股份有限公司",
    "Omnia Cybersystems": "Omnia网络系统公司",
    "Millenium Fitness Gym": "千禧健身馆",
    "CompuTek": "计算机科技公司",
    "Helios Labs": "太阳神实验室",
    "LexoCorp": "莱克索公司",
    "Tian Di Hui": "天地会",
    "Solaris Space Systems": "太阳系空间系统",
    "KuaiGong International": "凯通国际",
    "Four Sigma": "四西格玛",
    "Carmichael Security": "卡迈克尔安保",
    "Alpha Enterprises": "阿尔法企业",
    "The Slums": "贫民窟",
    "National Security Agency": "国家安全局",
    "Central Intelligence Agency": "中央情报局",
    "Blade Industries": "刀片工业",
    "FoodNStuff": "食品厂",
    "Hospital": "医院",
    "Joe's Guns": "乔的枪",
    "DeltaOne": "达美航空",
    "Iron Gym": "铁之健身房",
    "BruteSSH.exe": "BruteSSH.exe",
    "true": "true",
    "NUKE.exe": "NUKE.exe",
    "cb966f31": "cb966f31",
    "DeepscanV1.exe": "DeepscanV1.exe",
    "Discord": "Discord",
    "Reddit": "Reddit",
    "options": "选项",
    "home": "home",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Hacking": "黑客攻击",
    "Hacknet": "黑客网",
    "Hack": "黑客",
    "Money": "钱",
    "Defense": "防御",
    "Def": "防御",
    "HP": "生命值",
    "Strength": "力量",
    "Str": "力量",
    "Agility": "敏捷",
    "Agi": "敏捷",
    "Dexterity": "灵巧",
    "Dex": "灵巧",
    "Changelog": "更新日志",
    "Character": "角色",
    "Charisma": "魅力",
    "Cha": "魅力",
    "Bitburner v": "比特燃烧器 v",
    "Servers owned: ": "拥有的服务器：",
    "Augmentations installed: ": "增强已安装：",
    "Timestamp format:": "时间戳格式：",
    "Locale": "语言",
    " Nodes owned:": " 拥有的节点：",
//    "[blade industries]": "[刀片产业]",
//    " [hospital]": " [医院]",
//    " [megacorp]": " [大型企业]",
//    "[foodnstuff]": "[食品厂]",
//    "[powerhouse gym]": "[强力健身房]",
//    "[rothman university]": "[罗斯曼大学]",
//    "[universal energy]": "[宇宙能量]",
    "Sector-": "扇区-",
    "Error: Invalid file. Only scripts (.script, .ns, .js), or text files (.txt) can be edited with ": "错误：无效的文件。 只能使用脚本（.script、.ns、.js）或文本文件 (.txt) 进行编辑",
    "RAM: ": "内存: ",
    "Autosave interval (": "自动保存间隔 (",
    "Completing ": "完成 ",
    "hacknet-node-": "黑客网-节点-",
    "You've been Hospitalized for ": "你因住院治疗花费 ",
    "Purchase Hacknet Node -": "购买 黑客网 节点 -",
    "Buy 4S Market Data Access -": "购买4S市场数据访问权限 -",
    "Buy 4S Market Data TIX API Access -": "购买 4S 市场数据 TIX API 访问权限 -",
    "Buy Trade Information eXchange (TIX) API Access -": "购买贸易信息交换 (TIX) API 访问 -",
    "Buy WSE Account -": "购买 世界证券交易所（WSE） 账户 -",
    "Congratulations, you are now employed part-time at FoodNStuff": "恭喜您，您现在在 食品厂 兼职",
    "Purchase TOR router -": "购买TOR路由器 -",
    "ServerProfiler.exe": "ServerProfiler.exe",
    "Server": "服务器",
    " successfully purchased with hostname ": " 成功购买主机 ",
    "taking a Leadership course": "学习领导力课程",
    "NeuroFlux Governor - Level ": "神经通量 总督 - 等级 ",
    "Required hacking skill:": "所需的黑客技能：",
    "Required number of open ports for NUKE:": "NUKE 所需的开放端口数：",
    "Root Access: ": "Root访问权限：",
    "SMTP port: ": "SMTP 端口: ",
    "SQL port: ": "SQL 端口: ",
    "FTP port: ": "FTP 端口: ",
    "SSH port: ": "SSH 端口: ",
    "HTTP port: ": "HTTP 端口: ",
    "Total money available on server:": "服务器上可用的总资金：",
    "Total:": "总计:",
    "Available:": "可用:",
    "Augmentations:": "增强:",
    "Incorrect number of arguments. Usage:": "参数数量不正确。 用法：",
    "You already have root access to this computer. There is no reason to run ": "您已经拥有这台计算机的 root 访问权限。 没有理由运行 ",
    "Opened FTP Port (": "已打开 FTP 端口 (",
    "Opened SSH Port(": "已打开 SSH 端口（",
    "-RAM:": "-内存:",
    "Augmented Targeting ": "增强定位 ",
    "-Root Access: NO, Required hacking skill:": "-Root 权限：否，所需的黑客技能：",
    "-Number of open ports required to NUKE:": "- NUKE 所需的开放端口数：",
    "Congratulations! You were offered a new job at ": "恭喜！ 您获得了在 ",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    " Chance multiplier": " 几率乘数",
    " Experience multiplier": " 经验乘数",
    " Level multiplier": " 等级乘数",
    " Speed multiplier": " 速度乘数",
    " Money multiplier": " 金钱乘数",
    " Growth multiplier": " 成长乘数",
    " Node Core purchase cost multiplier": " 节点 核心购买 成本乘数",
    " Node purchase cost multiplier": " 节点 购买 成本乘数",
    " Node RAM upgrade cost multiplier": " 节点 内存升级 成本乘数",
    " Node production multiplier": " 节点 生产 成本乘数",
    " Node level upgrade cost multiplier": " 节点 等级升级 成本乘数",
//    "[travel agency]": "[旅行社]",
    "\/ sec": "\/ 秒",
    "Create or display Terminal aliases": "创建或显示终端别名",
    "Get information about the current machine": "获取当前机器的信息",
    "Install a backdoor on the current machine": "在当前机器上安装后门",
    "Purchase a program through the Dark Web": "通过暗网购买程序",
    "Display a .msg, .lit, or .txt file": "显示 .msg、.lit 或 .txt 文件",
    "Change to a new directory": "切换到新目录",
    "Print a script's logs to Terminal": "将脚本的日志打印到终端",
    "Clear all text on the terminal": "清除终端上的所有文本",
    "See 'clear' command": "请参阅“clear”命令",
    "Connects to a remote server": "连接到远程服务器",
    "Copy a file": "复制文件",
    "Downloads scripts or text files to your computer": "将脚本或文本文件下载到您的计算机",
    "Evaluate a mathematical expression": "计算数学表达式",
    "Check the machine's memory (RAM) usage": "检查机器的内存 (RAM) 使用情况",
    "Spoof money in a servers bank account, increasing the amount available.": "在服务器银行帐户中欺骗资金，增加可用金额。",
    "Hack the current machine": "破解当前机器",
    "Display this help text, or the help text for a command": "显示此帮助文本或命令的帮助文本",
    "Connect to home computer": "连接到家用电脑",
    "Displays the hostname of the machine": "显示机器的主机名",
    "Stops the specified script on the current server": "停止当前服务器上的指定脚本",
    "Stops all running scripts on the current machine": "停止当前机器上所有正在运行的脚本",
    "Displays all files on the machine": "显示机器上的所有文件",
    "Displays the number of CPU cores on the machine": "显示机器上的 CPU 核数",
    "Displays the amount of RAM required to run the script": "显示运行脚本所需的 RAM 量",
    "Move/rename a text or script file": "移动/重命名文本或脚本文件",
    "Text editor - Open up and edit one or more scripts or text files": "文本编辑器 - 打开和编辑一个或多个脚本或文本文件",
    "Display all scripts that are currently running": "显示当前正在运行的所有脚本",
    "Delete a file from the server": "从服务器删除文件",
    "Execute a program or script": "执行程序或脚本",
    "Prints all immediately-available network connections": "打印所有立即可用的网络连接",
    "Prints info for all servers up to <i>d</i> nodes away": "打印所有服务器的信息，最多 <i>d</i> 个节点",
    "Copies a file to a destination server": "将文件复制到目标服务器",
    "Shows whether you have root access on this computer": "显示您在这台计算机上是否具有 root 访问权限",
    "Displays dynamic logs for the specified script": "显示指定脚本的动态日志",
    "Displays all running scripts and their RAM usage": "显示所有正在运行的脚本及其 RAM 使用情况",
    "Deletes the specified alias": "删除指定的别名",
    "Text editor - Open up and edit one or more scripts or text files in vim mode": "文本编辑器 - 在 vi​​m 模式下打开和编辑一个或多个脚本或文本文件",
    "Reduce the security of the current machine": "降低当前机器的安全性",
    "Retrieves code/text from a web server": "从网络服务器检索代码/文本",
    " as a IT Intern!": " 上班的 IT 实习生 的新工作！",
    " as a Software Engineering Intern!": " 上班的 软件工程实习生 的新工作！",
    " as a Software Consultant!": " 上班的 软件顾问 的新工作！",
    " as a Business Intern!": " 上班的 商务实习生 的新工作！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) $/,
    /^([\d\.]+)GB$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Requires (.+) strength, (.+) defense, (.+) dexterity, (.+) agility, (.+) charisma$/, '需要 $1 力量，$2 防御，$3 灵巧，$4 敏捷，$5 魅力'],
    [/^Work(.+)in(.+)progress$/, '工作$1正在$2进行中'],
    [/^Security decreased from (.+) to (.+) \(min\: 1.000\) and Gained (.+) hacking exp.$/, '安全性从 $1 降至 $2（最低：1.000）并获得 $3 黑客经验。'],
    [/^Security increased from (.+) to (.+)$/, '安全性从 $1 增加到 $2'],
    [/^Do you want to save changes to (.+)\?$/, '是否要保存对 $1 的更改？'],
    [/^Time to hack\: (.+) seconds$/, '黑入时间：$1 秒'],
    [/^This message was saved as (.+) onto your home computer.$/, '此消息已作为 $1 保存到您的家用计算机上。'],
    [/^hack\: Executing (.+) in (.+) seconds \(t\=(.+)$/, 'hack：在 $2 秒内执行 $1 \(t=$3'],
    [/^Command (.+) not found$/, '命令 $1 未找到'],
    [/^Cannot (.+) your own machines! You are currently connected to your home PC or one of your purchased servers$/, '不能 $1 自己的机器！ 您当前已连接到您的家用 PC 或您购买的其中一台服务器'],
    [/^You've finished creating (.+)!$/, '您已经完成了 $1 的创建！'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
//    [/^(.+)\[icarus microsystems\](.+)$/, '$1\[伊卡洛斯微系统\]$2'],
//    [/^(.+)\[joe\'s guns\](.+)$/, '$1\[乔的枪\]$2'],
//    [/^(.+)\[iron gym\](.+)$/, '$1\[铁之健身房\]     $2'],
//    [/^(.+)\[deltaone\](.+)$/, '$1\[三角龙\]$2'],
//    [/^\[alpha ent.\](.+)$/, '\[阿尔法企业\]$1'],
//    [/^\[cia\](.+)$/, '\[中央情报局\]$1'],
//    [/^(.+)\[city hall\](.+)\[world stock exchange\]$/, '$1\[市政府\]$2\[世界证券交易所\]'],
//    [/^(.+)\[nsa\]$/, '$1\[安全局\]'],
//    [/^(.+)\[four sigma\]$/, '$1\[四西格玛\]'],
//    [/^(.+)\[the slums\]$/, '$1\[贫民窟\]'],
//    [/^(.+)\[carmichael sec.\]$/, '$1\[卡迈克尔安保\]'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^\-\$([\d\.]+)$/, '\-\$ $1'],
    [/^\$([\d\.]+)$/, '\$ $1'],
    [/^\$([\d\.]+) $/, '\$ $1 '],
    [/^\-\$([\d\.]+)$/, '\-\$ $1'],
    [/^\-\$([\d\.]+)k$/, '\-\$ $1k'],
    [/^\$\-([\d\.]+)k$/, '\$\- $1k'],
    [/^\-\$([\d\.]+)m$/, '\-\$ $1m'],
    [/^([\d\.]+)k$/, '$1k'],
    [/^\$([\d\.]+)k$/, '\$ $1k'],
    [/^\$([\d\.]+)m$/, '\$ $1m'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) hours ([\d\.,]+) seconds$/, '$1 小时 $2 秒'],
    [/^([\d\.,]+) minutes ([\d\.,]+) seconds$/, '$1 分钟 $2 秒'],
    [/^([\d\.,]+) days ([\d\.,]+) hours ([\d\.,]+) minutes ([\d\.,]+) seconds$/, '$1 天 $2 小时 $3分钟 $4 秒'],
    [/^([\d\.,]+) hours ([\d\.,]+) minutes ([\d\.,]+) seconds$/, '$1 小时 $2分钟 $3 秒'],
    [/^([\d\.,]+) charisma$/, '$1 魅力'],
    [/^([\d\.,]+) hacking$/, '$1 黑客'],
    [/^([\d\.,]+) agility$/, '$1 敏捷'],
    [/^([\d\.,]+) defense$/, '$1 防御'],
    [/^([\d\.,]+) City Hall$/, '$1 市政府'],
    [/^([\d\.,]+) dexterity$/, '$1 灵巧'],
    [/^([\d\.,]+) strength$/, '$1 力量'],
    [/^([\d\.,]+) reputation$/, '$1 名声'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Requires (.+) hacking$/, '需要 $1 黑客'],
    [/^Requires (.+) hacking, (.+) charisma$/, '需要 $1 黑客，$2 魅力'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);